# Fixed set of 12 demo dogs – same list used across Home, Prietenul tău, profiles, etc.
# Do not add more demo dogs; use this single source.
# Each dog has a unique imagine_fallback (static path) so A2 grid shows 12 different images.
# Optional: "added_at" (datetime) for A2 selection: dogs added in last 24h appear first in A2.
# "traits" = two personality traits for PT P2 card (max 2 shown).

DEMO_DOGS = [
    {"id": 1, "nume": "Charlie", "varsta": "2 ani", "descriere": "Prietenos și jucăuș, se înțelege cu copiii.", "imagine_fallback": "images/pets/charlie-400x200.jpg", "traits": ["Prietenos", "Jucăuș"]},
    {"id": 2, "nume": "Luna", "varsta": "4 ani", "descriere": "Liniștită, ideală pentru apartament.", "imagine_fallback": "images/pets/archie1-275x275.jpg", "traits": ["Liniștită", "Blândă"]},
    {"id": 3, "nume": "Max", "varsta": "3 ani", "descriere": "Energic, iubește plimbările lungi.", "imagine_fallback": "images/pets/candy1-275x275.jpeg", "traits": ["Energic", "Activist"]},
    {"id": 4, "nume": "Bella", "varsta": "5 ani", "descriere": "Dulce și devotată, adoptată din adăpost.", "imagine_fallback": "images/pets/chance1-275x275.jpg", "traits": ["Dulce", "Devotată"]},
    {"id": 5, "nume": "Rex", "varsta": "2 ani", "descriere": "Tânăr și curios, dresat la bază.", "imagine_fallback": "images/pets/chester1-275x275.jpg", "traits": ["Curios", "Dresat"]},
    {"id": 6, "nume": "Daisy", "varsta": "6 ani", "descriere": "Calmă, potrivită pentru familie.", "imagine_fallback": "images/pets/cindy1-275x275.jpg", "traits": ["Calmă", "Familie"]},
    {"id": 7, "nume": "Bruno", "varsta": "3 ani", "descriere": "Fidel și protectiv, bun paznic.", "imagine_fallback": "images/pets/grissom1-275x275.jpg", "traits": ["Fidel", "Protectiv"]},
    {"id": 8, "nume": "Mia", "varsta": "1 an", "descriere": "Pui activ, în căutare de jocuri.", "imagine_fallback": "images/pets/happy1-275x275.jpg", "traits": ["Activă", "Jucăușă"]},
    {"id": 9, "nume": "Rocky", "varsta": "4 ani", "descriere": "Rezistent, îi place natura.", "imagine_fallback": "images/pets/inga1-275x275.jpg", "traits": ["Rezistent", "Natură"]},
    {"id": 10, "nume": "Nala", "varsta": "2 ani", "descriere": "Sociabilă, se împrietenește cu alți câini.", "imagine_fallback": "images/pets/JazzyGirlAverill-1-275x275.jpg", "traits": ["Sociabilă", "Prietenoasă"]},
    {"id": 11, "nume": "Oscar", "varsta": "5 ani", "descriere": "Liniștit și afectuos, adaptat la interior.", "imagine_fallback": "images/pets/winston1-275x275.jpg", "traits": ["Liniștit", "Afectuos"]},
    {"id": 12, "nume": "Zara", "varsta": "3 ani", "descriere": "Inteligentă, răspunde bine la comenzi.", "imagine_fallback": "images/pets/shorty1-400x200.jpg", "traits": ["Inteligentă", "Ascultătoare"]},
]

# Fallback when a dog has no imagine_fallback (e.g. legacy code)
DEMO_DOG_IMAGE = "images/pets/charlie-400x200.jpg"

# Hero A1 (caseta cu sigle) – poze cu câini/animale care se rotesc în fundal.
# Dimensiuni recomandate: landscape 2:1 sau 3:1, ex. 1200×400 px sau 1600×500 px,
# min. 800×300 px. Pozele se afișează cu object-fit: cover (umplu banda, se decupează marginile).
HERO_SLIDER_IMAGES = [
    "images/pets/charlie-400x200.jpg",
    "images/pets/charlie-600x240.jpg",
    "images/pets/chester1-600x240.jpg",
    "images/pets/cindy1-600x240.jpg",
    "images/pets/shorty1-400x200.jpg",
]

# A2 homepage cover – quote pool (assign randomly to cards; rotate in JS)
A2_QUOTE_POOL = [
    "Sunt și eu un suflet.",
    "Caut o familie.",
    "Adoptă, nu cumpăra.",
    "Promit să te iubesc.",
    "Aștept o casă caldă.",
    "Vrei să fim prieteni?",
    "Un suflet te caută.",
    "Cineva te așteaptă.",
    "Împreună suntem familie.",
    "Dragostea nu se cumpără.",
    "Eu te aleg pe tine.",
    "Vrei să mă iei acasă?",
    "Sunt pregătit să iubesc.",
    "O șansă schimbă o viață.",
    "Casa ta poate fi casa mea.",
    "Un prieten adevărat.",
    "Sunt aici pentru tine.",
    "Adoptă un suflet.",
    "Nu cumpăra, adoptă.",
    "Familia începe cu iubire.",
    "Cineva te așteaptă acasă.",
    "Vreau să fiu prietenul tău.",
    "Un câine, o viață schimbată.",
    "Dragostea mea e gratuită.",
    "Am nevoie de tine.",
    "Vrei să fim echipă?",
    "Un prieten loial.",
    "Sunt gata de aventuri.",
    "Pot fi familia ta.",
    "Aștept o mângâiere.",
    "Un prieten pentru viață.",
    "Un suflet pentru un suflet.",
    "Îți pot schimba ziua.",
    "Împreună e mai bine.",
    "Te aștept.",
    "Adoptă speranță.",
]

# English pool for EU sites (.com / country TLDs)
A2_QUOTE_POOL_EN = [
    "I’m a soul too.",
    "Looking for a family.",
    "Adopt, don’t buy.",
    "I promise to love you.",
    "Waiting for a warm home.",
    "Want to be friends?",
    "A soul is looking for you.",
    "Someone is waiting.",
    "Together we are family.",
    "Love isn’t for sale.",
    "I choose you.",
    "Will you take me home?",
    "Ready to love.",
    "One chance changes a life.",
    "Your home can be mine.",
    "A true friend.",
    "I’m here for you.",
    "Adopt a soul.",
    "Don’t buy — adopt.",
    "Family starts with love.",
    "Someone waits for you at home.",
    "I want to be your friend.",
    "One dog, one life changed.",
    "My love is free.",
    "I need you.",
    "Want to be a team?",
    "A loyal friend.",
    "Ready for adventures.",
    "I can be your family.",
    "Waiting for a cuddle.",
    "A friend for life.",
    "A soul for a soul.",
    "I can change your day.",
    "Better together.",
    "I’m waiting for you.",
    "Adopt hope.",
]

A2_QUOTE_POOL_DE = [
    "Ich bin auch eine Seele.",
    "Ich suche eine Familie.",
    "Adoptiere, kaufe nicht.",
    "Ich verspreche, dich zu lieben.",
    "Ich warte auf ein warmes Zuhause.",
    "Wollen wir Freunde sein?",
    "Eine Seele sucht dich.",
    "Jemand wartet.",
    "Zusammen sind wir Familie.",
    "Liebe ist nicht käuflich.",
    "Ich wähle dich.",
    "Nimmst du mich mit nach Hause?",
    "Bereit zu lieben.",
    "Eine Chance verändert ein Leben.",
    "Dein Zuhause kann meins sein.",
    "Ein wahrer Freund.",
    "Ich bin für dich da.",
    "Adoptiere eine Seele.",
    "Nicht kaufen — adoptieren.",
    "Familie beginnt mit Liebe.",
    "Jemand wartet zu Hause auf dich.",
    "Ich möchte dein Freund sein.",
    "Ein Hund, ein verändertes Leben.",
    "Meine Liebe ist kostenlos.",
    "Ich brauche dich.",
    "Wollen wir ein Team sein?",
    "Ein treuer Freund.",
    "Bereit für Abenteuer.",
    "Ich kann deine Familie sein.",
    "Ich warte auf eine Streicheleinheit.",
    "Ein Freund fürs Leben.",
    "Eine Seele für eine Seele.",
    "Ich kann deinen Tag verändern.",
    "Zusammen ist es besser.",
    "Ich warte auf dich.",
    "Adoptiere Hoffnung.",
]

A2_QUOTE_POOL_FR = [
    "Moi aussi, je suis une âme.",
    "Je cherche une famille.",
    "Adopte, n’achète pas.",
    "Je promets de t’aimer.",
    "J’attends un foyer chaleureux.",
    "On devient amis ?",
    "Une âme te cherche.",
    "Quelqu’un t’attend.",
    "Ensemble, nous sommes une famille.",
    "L’amour ne s’achète pas.",
    "Je te choisis.",
    "Tu m’emmènes à la maison ?",
    "Prêt à aimer.",
    "Une chance change une vie.",
    "Ta maison peut être la mienne.",
    "Un vrai ami.",
    "Je suis là pour toi.",
    "Adopte une âme.",
    "N’achète pas — adopte.",
    "La famille commence par l’amour.",
    "Quelqu’un t’attend à la maison.",
    "Je veux être ton ami.",
    "Un chien, une vie changée.",
    "Mon amour est gratuit.",
    "J’ai besoin de toi.",
    "On forme une équipe ?",
    "Un ami fidèle.",
    "Prêt pour l’aventure.",
    "Je peux être ta famille.",
    "J’attends une caresse.",
    "Un ami pour la vie.",
    "Une âme pour une âme.",
    "Je peux changer ta journée.",
    "Ensemble, c’est mieux.",
    "Je t’attends.",
    "Adopte l’espoir.",
]

A2_QUOTE_POOL_ES = [
    "Yo también soy un alma.",
    "Busco una familia.",
    "Adopta, no compres.",
    "Prometo quererte.",
    "Espero un hogar cálido.",
    "¿Quieres ser amigos?",
    "Un alma te busca.",
    "Alguien te espera.",
    "Juntos somos familia.",
    "El amor no se compra.",
    "Te elijo a ti.",
    "¿Me llevas a casa?",
    "Listo para amar.",
    "Una oportunidad cambia una vida.",
    "Tu casa puede ser la mía.",
    "Un verdadero amigo.",
    "Estoy aquí para ti.",
    "Adopta un alma.",
    "No compres — adopta.",
    "La familia empieza con amor.",
    "Alguien te espera en casa.",
    "Quiero ser tu amigo.",
    "Un perro, una vida cambiada.",
    "Mi amor es gratis.",
    "Te necesito.",
    "¿Queremos ser un equipo?",
    "Un amigo leal.",
    "Listo para aventuras.",
    "Puedo ser tu familia.",
    "Espero una caricia.",
    "Un amigo para toda la vida.",
    "Un alma para un alma.",
    "Puedo cambiar tu día.",
    "Juntos es mejor.",
    "Te espero.",
    "Adopta esperanza.",
]

# Limbi TLD / hub pentru mottouri Home A2
A2_QUOTE_POOLS_BY_LANG: dict[str, list[str]] = {
    "en": A2_QUOTE_POOL_EN,
    "de": A2_QUOTE_POOL_DE,
    "fr": A2_QUOTE_POOL_FR,
    "es": A2_QUOTE_POOL_ES,
}
