"""
Etichete navbar EU hub — toate limbile UE + EN (fără .mo).
Fallback: engleză.
"""
from __future__ import annotations

from home.eu_site import EU_SITE_DEFAULT_LANGUAGE, EU_SITE_LANGUAGE_CODES

# Chei obligatorii pe fiecare limbă
_KEYS = (
    "home",
    "pets",
    "shelters",
    "mypet",
    "ilove",
    "login_cta",
    "logout",
    "terms",
    "contact",
    "on_site",
    "adopted",
    "search_ph",
    "lang_label",
    "open_menu",
    "close_menu",
    "eu_blocked",
)

_EN: dict[str, str] = {
    "home": "Home",
    "pets": "Find a friend",
    "shelters": "Shelters / NGOs",
    "mypet": "MyPet",
    "ilove": "I Love",
    "login_cta": "Sign in / Register",
    "logout": "Log out",
    "terms": "Terms",
    "contact": "Contact",
    "on_site": "On site",
    "adopted": "Adopted",
    "search_ph": "Search…",
    "lang_label": "Language",
    "open_menu": "Open menu",
    "close_menu": "Close menu",
    "eu_blocked": "This section is not available on the European site.",
}


def _pack(**overrides: str) -> dict[str, str]:
    out = dict(_EN)
    out.update(overrides)
    return out


_LABELS: dict[str, dict[str, str]] = {
    "en": dict(_EN),
    "de": _pack(
        home="Start",
        pets="Finde einen Freund",
        shelters="Tierheime / NGOs",
        login_cta="Anmelden / Registrieren",
        logout="Abmelden",
        terms="AGB",
        contact="Kontakt",
        on_site="Online",
        adopted="Adoptiert",
        search_ph="Suchen…",
        lang_label="Sprache",
        open_menu="Menü öffnen",
        close_menu="Menü schließen",
        eu_blocked="Dieser Bereich ist auf der europäischen Website nicht verfügbar.",
    ),
    "fr": _pack(
        home="Accueil",
        pets="Trouver un ami",
        shelters="Refuges / ONG",
        login_cta="Connexion / Inscription",
        logout="Déconnexion",
        terms="Conditions",
        contact="Contact",
        on_site="Sur le site",
        adopted="Adoptés",
        search_ph="Rechercher…",
        lang_label="Langue",
        open_menu="Ouvrir le menu",
        close_menu="Fermer le menu",
        eu_blocked="Cette section n’est pas disponible sur le site européen.",
    ),
    "es": _pack(
        home="Inicio",
        pets="Encuentra un amigo",
        shelters="Refugios / ONG",
        login_cta="Entrar / Registrarse",
        logout="Salir",
        terms="Términos",
        contact="Contacto",
        on_site="En el sitio",
        adopted="Adoptados",
        search_ph="Buscar…",
        lang_label="Idioma",
        open_menu="Abrir menú",
        close_menu="Cerrar menú",
        eu_blocked="Esta sección no está disponible en el sitio europeo.",
    ),
    "it": _pack(
        home="Home",
        pets="Trova un amico",
        shelters="Rifugi / ONG",
        login_cta="Accedi / Registrati",
        logout="Esci",
        terms="Termini",
        contact="Contatto",
        on_site="Sul sito",
        adopted="Adottati",
        search_ph="Cerca…",
        lang_label="Lingua",
        open_menu="Apri menu",
        close_menu="Chiudi menu",
        eu_blocked="Questa sezione non è disponibile sul sito europeo.",
    ),
    "pt": _pack(
        home="Início",
        pets="Encontre um amigo",
        shelters="Abrigos / ONG",
        login_cta="Entrar / Registar",
        logout="Sair",
        terms="Termos",
        contact="Contacto",
        on_site="No site",
        adopted="Adotados",
        search_ph="Pesquisar…",
        lang_label="Idioma",
        open_menu="Abrir menu",
        close_menu="Fechar menu",
        eu_blocked="Esta secção não está disponível no site europeu.",
    ),
    "nl": _pack(
        home="Home",
        pets="Vind een vriend",
        shelters="Asielen / NGO's",
        login_cta="Inloggen / Registreren",
        logout="Uitloggen",
        terms="Voorwaarden",
        contact="Contact",
        on_site="Op site",
        adopted="Geadopteerd",
        search_ph="Zoeken…",
        lang_label="Taal",
        open_menu="Menu openen",
        close_menu="Menu sluiten",
        eu_blocked="Dit onderdeel is niet beschikbaar op de Europese site.",
    ),
    "pl": _pack(
        home="Strona główna",
        pets="Znajdź przyjaciela",
        shelters="Schroniska / NGO",
        login_cta="Zaloguj / Rejestracja",
        logout="Wyloguj",
        terms="Regulamin",
        contact="Kontakt",
        on_site="Na stronie",
        adopted="Adoptowane",
        search_ph="Szukaj…",
        lang_label="Język",
        open_menu="Otwórz menu",
        close_menu="Zamknij menu",
        eu_blocked="Ta sekcja nie jest dostępna na europejskiej stronie.",
    ),
    "ro": _pack(
        home="Acasă",
        pets="Prietenul tău",
        shelters="Adăpost / ONG",
        login_cta="Intră / Fă cont",
        logout="Deconectare",
        terms="Termeni",
        contact="Contact",
        on_site="În site",
        adopted="Adoptați",
        search_ph="Căutare…",
        lang_label="Limbă",
        open_menu="Deschide meniul",
        close_menu="Închide meniul",
        eu_blocked="Această secțiune nu este disponibilă pe site-ul european.",
    ),
    "cs": _pack(
        home="Domů",
        pets="Najdi přítele",
        shelters="Útulky / NGO",
        login_cta="Přihlásit / Registrace",
        logout="Odhlásit",
        terms="Podmínky",
        contact="Kontakt",
        on_site="Na webu",
        adopted="Adoptováno",
        search_ph="Hledat…",
        lang_label="Jazyk",
        open_menu="Otevřít menu",
        close_menu="Zavřít menu",
        eu_blocked="Tato sekce není na evropském webu dostupná.",
    ),
    "sk": _pack(
        home="Domov",
        pets="Nájdi priateľa",
        shelters="Útulky / NGO",
        login_cta="Prihlásiť / Registrácia",
        logout="Odhlásiť",
        terms="Podmienky",
        contact="Kontakt",
        on_site="Na webe",
        adopted="Adoptované",
        search_ph="Hľadať…",
        lang_label="Jazyk",
        open_menu="Otvoriť menu",
        close_menu="Zavrieť menu",
        eu_blocked="Táto sekcia nie je na európskom webe dostupná.",
    ),
    "hu": _pack(
        home="Kezdőlap",
        pets="Barát keresése",
        shelters="Menhelyek / NGO",
        login_cta="Belépés / Regisztráció",
        logout="Kilépés",
        terms="Feltételek",
        contact="Kapcsolat",
        on_site="Az oldalon",
        adopted="Örökbe fogadva",
        search_ph="Keresés…",
        lang_label="Nyelv",
        open_menu="Menü megnyitása",
        close_menu="Menü bezárása",
        eu_blocked="Ez a rész nem érhető el az európai oldalon.",
    ),
    "bg": _pack(
        home="Начало",
        pets="Намери приятел",
        shelters="Приюти / НПО",
        login_cta="Вход / Регистрация",
        logout="Изход",
        terms="Условия",
        contact="Контакт",
        on_site="На сайта",
        adopted="Осиновени",
        search_ph="Търсене…",
        lang_label="Език",
        open_menu="Отвори меню",
        close_menu="Затвори меню",
        eu_blocked="Този раздел не е наличен в европейския сайт.",
    ),
    "hr": _pack(
        home="Početna",
        pets="Pronađi prijatelja",
        shelters="Skloništa / NGO",
        login_cta="Prijava / Registracija",
        logout="Odjava",
        terms="Uvjeti",
        contact="Kontakt",
        on_site="Na stranici",
        adopted="Usvojeno",
        search_ph="Traži…",
        lang_label="Jezik",
        open_menu="Otvori izbornik",
        close_menu="Zatvori izbornik",
        eu_blocked="Ovaj odjeljak nije dostupan na europskoj stranici.",
    ),
    "sl": _pack(
        home="Domov",
        pets="Najdi prijatelja",
        shelters="Zavetišča / NGO",
        login_cta="Prijava / Registracija",
        logout="Odjava",
        terms="Pogoji",
        contact="Kontakt",
        on_site="Na strani",
        adopted="Posvojeno",
        search_ph="Išči…",
        lang_label="Jezik",
        open_menu="Odpri meni",
        close_menu="Zapri meni",
        eu_blocked="Ta razdelek ni na voljo na evropskem spletnem mestu.",
    ),
    "et": _pack(
        home="Avaleht",
        pets="Leia sõber",
        shelters="Varjupaigad / MTÜ",
        login_cta="Logi sisse / Registreeru",
        logout="Logi välja",
        terms="Tingimused",
        contact="Kontakt",
        on_site="Lehel",
        adopted="Adopteeritud",
        search_ph="Otsi…",
        lang_label="Keel",
        open_menu="Ava menüü",
        close_menu="Sulge menüü",
        eu_blocked="See jaotis ei ole Euroopa saidil saadaval.",
    ),
    "lv": _pack(
        home="Sākums",
        pets="Atrodi draugu",
        shelters="Patversmes / NVO",
        login_cta="Pieteikties / Reģistrēties",
        logout="Iziet",
        terms="Noteikumi",
        contact="Kontakti",
        on_site="Vietnē",
        adopted="Adoptēti",
        search_ph="Meklēt…",
        lang_label="Valoda",
        open_menu="Atvērt izvēlni",
        close_menu="Aizvērt izvēlni",
        eu_blocked="Šī sadaļa nav pieejama Eiropas vietnē.",
    ),
    "lt": _pack(
        home="Pradžia",
        pets="Rask draugą",
        shelters="Prieglaudos / NVO",
        login_cta="Prisijungti / Registruotis",
        logout="Atsijungti",
        terms="Sąlygos",
        contact="Kontaktai",
        on_site="Svetainėje",
        adopted="Įvaikinti",
        search_ph="Ieškoti…",
        lang_label="Kalba",
        open_menu="Atidaryti meniu",
        close_menu="Uždaryti meniu",
        eu_blocked="Šis skyrius nėra pasiekiamas europinėje svetainėje.",
    ),
    "fi": _pack(
        home="Etusivu",
        pets="Löydä ystävä",
        shelters="Turvakodit / NGO",
        login_cta="Kirjaudu / Rekisteröidy",
        logout="Kirjaudu ulos",
        terms="Ehdot",
        contact="Yhteystiedot",
        on_site="Sivustolla",
        adopted="Adoptoidut",
        search_ph="Haku…",
        lang_label="Kieli",
        open_menu="Avaa valikko",
        close_menu="Sulje valikko",
        eu_blocked="Tämä osio ei ole saatavilla eurooppalaisella sivustolla.",
    ),
    "sv": _pack(
        home="Hem",
        pets="Hitta en vän",
        shelters="Hem / NGO",
        login_cta="Logga in / Registrera",
        logout="Logga ut",
        terms="Villkor",
        contact="Kontakt",
        on_site="På webben",
        adopted="Adopterade",
        search_ph="Sök…",
        lang_label="Språk",
        open_menu="Öppna meny",
        close_menu="Stäng meny",
        eu_blocked="Denna sektion är inte tillgänglig på den europeiska webbplatsen.",
    ),
    "da": _pack(
        home="Hjem",
        pets="Find en ven",
        shelters="Internater / NGO",
        login_cta="Log ind / Tilmeld",
        logout="Log ud",
        terms="Vilkår",
        contact="Kontakt",
        on_site="På siden",
        adopted="Adopteret",
        search_ph="Søg…",
        lang_label="Sprog",
        open_menu="Åbn menu",
        close_menu="Luk menu",
        eu_blocked="Denne sektion er ikke tilgængelig på det europæiske site.",
    ),
    "el": _pack(
        home="Αρχική",
        pets="Βρες φίλο",
        shelters="Καταφύγια / ΜΚΟ",
        login_cta="Σύνδεση / Εγγραφή",
        logout="Έξοδος",
        terms="Όροι",
        contact="Επικοινωνία",
        on_site="Στο site",
        adopted="Υιοθετημένα",
        search_ph="Αναζήτηση…",
        lang_label="Γλώσσα",
        open_menu="Άνοιγμα μενού",
        close_menu="Κλείσιμο μενού",
        eu_blocked="Αυτή η ενότητα δεν είναι διαθέσιμη στον ευρωπαϊκό ιστότοπο.",
    ),
    "ga": _pack(
        home="Baile",
        pets="Aimsigh cara",
        shelters="Dídean / NGO",
        login_cta="Logáil isteach / Cláraigh",
        logout="Logáil amach",
        terms="Téarmaí",
        contact="Teagmháil",
        on_site="Ar an suíomh",
        adopted="Uchtaithe",
        search_ph="Cuardaigh…",
        lang_label="Teanga",
        open_menu="Oscail an roghchlár",
        close_menu="Dún an roghchlár",
        eu_blocked="Níl an chuid seo ar fáil ar an suíomh Eorpach.",
    ),
    "mt": _pack(
        home="Dar",
        pets="Sib ħabib",
        shelters="Kennels / NGO",
        login_cta="Idħol / Irreġistra",
        logout="Oħroġ",
        terms="Termini",
        contact="Kuntatt",
        on_site="Fuq is-sit",
        adopted="Adottati",
        search_ph="Fittex…",
        lang_label="Lingwa",
        open_menu="Iftaħ il-menu",
        close_menu="Agħlaq il-menu",
        eu_blocked="Din it-taqsima mhix disponibbli fuq is-sit Ewropew.",
    ),
}


def eu_nav_label(lang: str, key: str) -> str:
    code = (lang or EU_SITE_DEFAULT_LANGUAGE).split("-")[0].lower()
    if code not in EU_SITE_LANGUAGE_CODES:
        code = EU_SITE_DEFAULT_LANGUAGE
    pack = _LABELS.get(code) or _LABELS[EU_SITE_DEFAULT_LANGUAGE]
    return pack.get(key) or _EN.get(key) or key


def assert_all_languages_complete() -> None:
    """Helper teste: fiecare limbă UE are toate cheile."""
    missing = []
    for code in sorted(EU_SITE_LANGUAGE_CODES):
        pack = _LABELS.get(code)
        if not pack:
            missing.append(f"{code}: no pack")
            continue
        for key in _KEYS:
            if key not in pack or not str(pack[key]).strip():
                missing.append(f"{code}.{key}")
    if missing:
        raise AssertionError("Incomplete EU nav labels: " + ", ".join(missing[:40]))
