"""
Etichete navbar EU hub — traduceri scurte per limbă (fără .mo).
Fallback: engleză.
"""
from __future__ import annotations

from home.eu_site import EU_SITE_DEFAULT_LANGUAGE, EU_SITE_LANGUAGE_CODES

# Chei: home, pets, shelters, mypet, ilove, login_cta, logout, terms, contact,
# on_site, adopted, search_ph, lang_label, open_menu, close_menu

_EN: dict[str, str] = {
    "home": "Home",
    "pets": "Find a friend",
    "shelters": "Shelters / NGOs",
    "mypet": "MyPet",
    "ilove": "I Love",
    "login_cta": "Sign in / Register",
    "logout": "Log out",
    "terms": "Terms",
    "contact": "Contact",
    "on_site": "On site",
    "adopted": "Adopted",
    "search_ph": "Search…",
    "lang_label": "Language",
    "open_menu": "Open menu",
    "close_menu": "Close menu",
    "eu_blocked": "This section is not available on the European site.",
}

_LABELS: dict[str, dict[str, str]] = {
    "en": _EN,
    "de": {
        **_EN,
        "home": "Start",
        "pets": "Finde einen Freund",
        "shelters": "Tierheime / NGOs",
        "mypet": "MyPet",
        "ilove": "I Love",
        "login_cta": "Anmelden / Registrieren",
        "logout": "Abmelden",
        "terms": "AGB",
        "contact": "Kontakt",
        "on_site": "Online",
        "adopted": "Adoptiert",
        "search_ph": "Suchen…",
        "lang_label": "Sprache",
        "open_menu": "Menü öffnen",
        "close_menu": "Menü schließen",
    },
    "fr": {
        **_EN,
        "home": "Accueil",
        "pets": "Trouver un ami",
        "shelters": "Refuges / ONG",
        "login_cta": "Connexion / Inscription",
        "logout": "Déconnexion",
        "terms": "Conditions",
        "contact": "Contact",
        "on_site": "Sur le site",
        "adopted": "Adoptés",
        "search_ph": "Rechercher…",
        "lang_label": "Langue",
        "open_menu": "Ouvrir le menu",
        "close_menu": "Fermer le menu",
    },
    "es": {
        **_EN,
        "home": "Inicio",
        "pets": "Encuentra un amigo",
        "shelters": "Refugios / ONG",
        "login_cta": "Entrar / Registrarse",
        "logout": "Salir",
        "terms": "Términos",
        "contact": "Contacto",
        "on_site": "En el sitio",
        "adopted": "Adoptados",
        "search_ph": "Buscar…",
        "lang_label": "Idioma",
    },
    "it": {
        **_EN,
        "home": "Home",
        "pets": "Trova un amico",
        "shelters": "Rifugi / ONG",
        "login_cta": "Accedi / Registrati",
        "logout": "Esci",
        "terms": "Termini",
        "contact": "Contatto",
        "on_site": "Sul sito",
        "adopted": "Adottati",
        "search_ph": "Cerca…",
        "lang_label": "Lingua",
    },
    "pt": {
        **_EN,
        "home": "Início",
        "pets": "Encontre um amigo",
        "shelters": "Abrigos / ONG",
        "login_cta": "Entrar / Registar",
        "logout": "Sair",
        "terms": "Termos",
        "contact": "Contacto",
        "on_site": "No site",
        "adopted": "Adotados",
        "search_ph": "Pesquisar…",
        "lang_label": "Idioma",
    },
    "nl": {
        **_EN,
        "home": "Home",
        "pets": "Vind een vriend",
        "shelters": "Asielen / NGO's",
        "login_cta": "Inloggen / Registreren",
        "logout": "Uitloggen",
        "terms": "Voorwaarden",
        "contact": "Contact",
        "on_site": "Op site",
        "adopted": "Geadopteerd",
        "search_ph": "Zoeken…",
        "lang_label": "Taal",
    },
    "pl": {
        **_EN,
        "home": "Strona główna",
        "pets": "Znajdź przyjaciela",
        "shelters": "Schroniska / NGO",
        "login_cta": "Zaloguj / Rejestracja",
        "logout": "Wyloguj",
        "terms": "Regulamin",
        "contact": "Kontakt",
        "on_site": "Na stronie",
        "adopted": "Adoptowane",
        "search_ph": "Szukaj…",
        "lang_label": "Język",
    },
    "ro": {
        **_EN,
        "home": "Acasă",
        "pets": "Prietenul tău",
        "shelters": "Adăpost / ONG",
        "login_cta": "Intră / Fă cont",
        "logout": "Logout",
        "terms": "Termeni",
        "contact": "Contact",
        "on_site": "În site",
        "adopted": "Adoptați",
        "search_ph": "Căutare…",
        "lang_label": "Limbă",
    },
    "cs": {
        **_EN,
        "home": "Domů",
        "pets": "Najdi přítele",
        "shelters": "Útulky / NGO",
        "login_cta": "Přihlásit / Registrace",
        "logout": "Odhlásit",
        "terms": "Podmínky",
        "contact": "Kontakt",
        "on_site": "Na webu",
        "adopted": "Adoptováno",
        "lang_label": "Jazyk",
    },
    "sk": {
        **_EN,
        "home": "Domov",
        "pets": "Nájdi priateľa",
        "shelters": "Útulky / NGO",
        "login_cta": "Prihlásiť / Registrácia",
        "logout": "Odhlásiť",
        "terms": "Podmienky",
        "contact": "Kontakt",
        "on_site": "Na webe",
        "adopted": "Adoptované",
        "lang_label": "Jazyk",
    },
    "hu": {
        **_EN,
        "home": "Kezdőlap",
        "pets": "Barát keresése",
        "shelters": "Menhelyek / NGO",
        "login_cta": "Belépés / Regisztráció",
        "logout": "Kilépés",
        "terms": "Feltételek",
        "contact": "Kapcsolat",
        "on_site": "Az oldalon",
        "adopted": "Örökbe fogadva",
        "lang_label": "Nyelv",
    },
    "bg": {
        **_EN,
        "home": "Начало",
        "pets": "Намери приятел",
        "shelters": "Приюти / НПО",
        "login_cta": "Вход / Регистрация",
        "logout": "Изход",
        "terms": "Условия",
        "contact": "Контакт",
        "on_site": "На сайта",
        "adopted": "Осиновени",
        "lang_label": "Език",
    },
    "hr": {
        **_EN,
        "home": "Početna",
        "pets": "Pronađi prijatelja",
        "shelters": "Skloništa / NGO",
        "login_cta": "Prijava / Registracija",
        "logout": "Odjava",
        "terms": "Uvjeti",
        "contact": "Kontakt",
        "on_site": "Na stranici",
        "adopted": "Usvojeno",
        "lang_label": "Jezik",
    },
    "sl": {
        **_EN,
        "home": "Domov",
        "pets": "Najdi prijatelja",
        "shelters": "Zavetišča / NGO",
        "login_cta": "Prijava / Registracija",
        "logout": "Odjava",
        "terms": "Pogoji",
        "contact": "Kontakt",
        "on_site": "Na strani",
        "adopted": "Posvojeno",
        "lang_label": "Jezik",
    },
    "et": {
        **_EN,
        "home": "Avaleht",
        "pets": "Leia sõber",
        "shelters": "Varjupaigad / MTÜ",
        "login_cta": "Logi sisse / Registreeru",
        "logout": "Logi välja",
        "terms": "Tingimused",
        "contact": "Kontakt",
        "on_site": "Lehel",
        "adopted": "Adopteeritud",
        "lang_label": "Keel",
    },
    "lv": {
        **_EN,
        "home": "Sākums",
        "pets": "Atrodi draugu",
        "shelters": "Patversmes / NVO",
        "login_cta": "Pieteikties / Reģistrēties",
        "logout": "Iziet",
        "terms": "Noteikumi",
        "contact": "Kontakti",
        "on_site": "Vietnē",
        "adopted": "Adoptēti",
        "lang_label": "Valoda",
    },
    "lt": {
        **_EN,
        "home": "Pradžia",
        "pets": "Rask draugą",
        "shelters": "Prieglaudos / NVO",
        "login_cta": "Prisijungti / Registruotis",
        "logout": "Atsijungti",
        "terms": "Sąlygos",
        "contact": "Kontaktai",
        "on_site": "Svetainėje",
        "adopted": "Įvaikinti",
        "lang_label": "Kalba",
    },
    "fi": {
        **_EN,
        "home": "Etusivu",
        "pets": "Löydä ystävä",
        "shelters": "Turvakodit / NGO",
        "login_cta": "Kirjaudu / Rekisteröidy",
        "logout": "Kirjaudu ulos",
        "terms": "Ehdot",
        "contact": "Yhteystiedot",
        "on_site": "Sivustolla",
        "adopted": "Adoptoidut",
        "lang_label": "Kieli",
    },
    "sv": {
        **_EN,
        "home": "Hem",
        "pets": "Hitta en vän",
        "shelters": "Hem / NGO",
        "login_cta": "Logga in / Registrera",
        "logout": "Logga ut",
        "terms": "Villkor",
        "contact": "Kontakt",
        "on_site": "På webben",
        "adopted": "Adopterade",
        "lang_label": "Språk",
    },
    "da": {
        **_EN,
        "home": "Hjem",
        "pets": "Find en ven",
        "shelters": "Internater / NGO",
        "login_cta": "Log ind / Tilmeld",
        "logout": "Log ud",
        "terms": "Vilkår",
        "contact": "Kontakt",
        "on_site": "På siden",
        "adopted": "Adopteret",
        "lang_label": "Sprog",
    },
    "el": {
        **_EN,
        "home": "Αρχική",
        "pets": "Βρες φίλο",
        "shelters": "Καταφύγια / ΜΚΟ",
        "login_cta": "Σύνδεση / Εγγραφή",
        "logout": "Έξοδος",
        "terms": "Όροι",
        "contact": "Επικοινωνία",
        "on_site": "Στο site",
        "adopted": "Υιοθετημένα",
        "lang_label": "Γλώσσα",
    },
    "ga": {
        **_EN,
        "home": "Baile",
        "pets": "Aimsigh cara",
        "shelters": "Fothracha / NGO",
        "login_cta": "Logáil isteach / Cláraigh",
        "logout": "Logáil amach",
        "terms": "Téarmaí",
        "contact": "Teagmháil",
        "on_site": "Ar an suíomh",
        "adopted": "Uchtaithe",
        "lang_label": "Teanga",
    },
    "mt": {
        **_EN,
        "home": "Home",
        "pets": "Sib ħabib",
        "shelters": "Kennels / NGO",
        "login_cta": "Idħol / Irreġistra",
        "logout": "Oħroġ",
        "terms": "Termini",
        "contact": "Kuntatt",
        "on_site": "Fuq is-site",
        "adopted": "Adottati",
        "lang_label": "Lingwa",
    },
}


def eu_nav_label(lang: str, key: str) -> str:
    code = (lang or EU_SITE_DEFAULT_LANGUAGE).split("-")[0].lower()
    if code not in EU_SITE_LANGUAGE_CODES:
        code = EU_SITE_DEFAULT_LANGUAGE
    pack = _LABELS.get(code) or _LABELS[EU_SITE_DEFAULT_LANGUAGE]
    return pack.get(key) or _EN.get(key) or key
