"""
UI page strings for EU sites — English forced on .com (full UI).
Romanian stays hard-coded on .ro templates via eu_t / if eu_site_active fallback.
"""
from __future__ import annotations

_EN: dict[str, str] = {
    # Common / chrome
    "messages_new": "New messages: {n}",
    "messages_none": "No new messages",
    "messages_title_new": "New messages: {n}",
    "messages_title_none": "No new messages",
    "loading": "Loading…",
    "save": "Save",
    "cancel": "Cancel",
    "close": "Close",
    "send": "Send",
    "search": "Search",
    "back": "Back",
    "next": "Next",
    "yes": "Yes",
    "no": "No",
    "error": "Something went wrong. Please try again.",
    "required": "Required",
    "email": "Email",
    "policy": "Policy",
    "response_time": "Response time",
    "working_days": "1–3 working days",
    "in_progress": "to be completed",
    # Login / Intra
    "login_title": "Sign in – EU-ADOPT",
    "login_heading": "Sign in",
    "login_sub": "Simple sign-in to manage your listings and preferences.",
    "login_user": "Email / username",
    "login_user_ph": "email or username",
    "login_password": "Password",
    "login_show_pass": "Show password",
    "login_submit": "Sign in",
    "login_forgot": "Forgot your password?",
    "login_no_account": "No account yet?",
    "login_create": "Create account",
    "login_failed": "Sign-in failed.",
    "login_reset_ok": "Password was reset.",
    "login_reset_ok_hint": "Sign in with your new password.",
    "login_aria": "EU-ADOPT sign-in",
    # Contact
    "contact_title": "Contact | EU-ADOPT",
    "contact_heading": "Contact EU-ADOPT",
    "contact_intro": "Choose the right channel and email us. We usually reply within 1–3 working days.",
    "contact_emails_h": "EU-Adopt email addresses",
    "contact_emails_lead": "Tap Send email — your mail app opens with the recipient filled in.",
    "contact_send_email": "Send email",
    "contact_emails_note": "All messages are handled by the EU-Adopt team. For animal medical emergencies, contact a vet immediately.",
    "contact_aria": "Contact page",
    "contact_legal_h": "Platform operator details",
    "contact_legal_name": "Legal name:",
    "contact_legal_cui": "Company ID:",
    "contact_legal_hq": "Registered office:",
    "contact_legal_phone": "Phone:",
    "contact_legal_email": "General email:",
    "contact_card1_h": "1) General support",
    "contact_card1_p": "Account, sign-in, using the pages and technical issues.",
    "contact_card2_h": "2) Personal data (GDPR)",
    "contact_card2_p": "Access, rectification, erasure, restriction, portability, objection.",
    "contact_card2_pol": "Privacy",
    "contact_card3_h": "3) Advertising and paid services",
    "contact_card3_p": "Promotion, campaigns, slots and paid appearances.",
    "contact_card3_pol": "Paid services",
    "contact_card4_h": "4) Moderation and reports",
    "contact_card4_p": "Suspect content, abusive accounts, fraud or rule breaches.",
    "contact_card4_pol": "Moderation",
    # Terms hub
    "terms_title": "Terms | EU-ADOPT",
    "terms_heading": "Legal documents – EU-ADOPT",
    "terms_intro": "Choose the document you want to read.",
    "terms_cat1": "1) Terms and conditions",
    "terms_cat1_sub": "General rules of use",
    "terms_cat2": "2) Privacy policy",
    "terms_cat2_sub": "Protection of personal data",
    "terms_cat3": "3) Additional policies",
    "terms_cat3_sub": "Cookies, paid services and moderation",
    "terms_aria": "Legal documents hub",
    "terms_en_note": "Full legal text is currently in Romanian. An English version is being prepared; the Romanian documents remain the legally binding version.",
    # 404
    "err404_title": "Page not found | EU-Adopt",
    "err404_h1": "This page does not exist",
    "err404_body": "The address was not found or has been moved.",
    "err404_home": "Back to home",
    # Home
    "home_title": "EU Adopt – Home",
    "home_meta": "EU-ADOPT Home – dog and cat adoption across Europe, listings and pet services.",
    "home_mission_adopted": "In our care: {n} adopted",
    "home_mission_looking": "pets looking for a home right now",
    "home_mission_cta": "Be part of the journey →",
    "home_mission_cta_title": "Support the project — donations",
    "home_welcome_title": "Welcome to EU-Adopt",
    "home_welcome_p1": "Animals are not bought or sold here. Together, we help them find a home and someone who will love them.",
    "home_welcome_p2": "On EU-Adopt you can:",
    "home_welcome_li1": "discover animals from NGOs and shelters waiting for a family;",
    "home_welcome_li2": "support NGOs by buying a photo or styled item in the Shop — your contribution goes to them;",
    "home_welcome_li3": "receive small benefits for every confirmed adoption, as a thank-you;",
    "home_welcome_li4": "share animals on social media and increase both their chance of a home and your chance of monthly prizes.",
    "home_welcome_p3": "Every visit and every share can change an animal’s story. Thank you for being here.",
    "home_welcome_close_hint": "(Close this note and continue on EU-Adopt.)",
    "home_welcome_close_btn": "Close",
    "home_a2_aria": "12 dogs available for adoption",
    "home_pub_aria_top": "Sponsored listings – top",
    "home_pub_aria_bottom": "Sponsored listings – bottom",
    "home_burtiera_aria": "EU-Adopt notice",
    "home_burtiera_default": "#EuAdopt #DontBuy – EU-Adopt is an independent initiative promoting animal adoption. This project is not affiliated with, funded by, or run by the European Union.",
    "home_note_share": "Share EU-Adopt, support a transport or a crate, buy a photo from the photo shop or promote a listing for visibility – never buying or selling animals on the site.",
    "home_note_share_guest": "Share EU-Adopt, support a transport or a crate, or buy a photo from the photo shop – never buying or selling animals on the site.",
    "home_cta_support": "Support EU-Adopt",
    "home_cta_pets": "Come meet us!",
    "home_cta_pets_title": "See your friends",
    "home_note_close": "Close note",
    "home_note_title": "Quick guide – EU-Adopt pages",
    "home_note_rule": "Important rule: animals are not bought or sold on this site. Adoption happens by request and agreement with the keeper or NGO — not through commercial transactions on the platform.",
    "home_note_home_h": "Home",
    "home_note_home_p": "Overview, adoption listings grid and quick access to other sections.",
    "home_note_pt_h": "Find a friend",
    "home_note_pt_p_auth": "List of available animals; filters; open a profile for details, messages and adoption request. The heart saves the animal in I Love.",
    "home_note_pt_p_guest": "List of available animals; filters; open a profile for details, messages and adoption request. After you sign in, you can use the heart to save animals on the I Love page.",
    "home_note_ficha_h": "Animal profile (subpage)",
    "home_note_ficha_p": "Animal details, messages to the keeper, adoption flow. Promoting in the A2 grid is paid visibility for the listing — it does not mean buying the animal.",
    "home_note_svc_h": "Services",
    "home_note_svc_p": "Partner services (e.g. clinic, training) related to animal care — not trade in animals.",
    "home_note_tr_h": "Transport",
    "home_note_tr_p": "Logistics support for adoptions and donations (e.g. crates). Always outside any animal sale.",
    "home_note_crates_h": "Crates",
    "home_note_crates_p": "Info and involvement for donating transport crates — unrelated to selling animals.",
    "home_note_shop_h": "Shop",
    "home_note_shop_p": "Products and materials; proceeds support the cause. There is no “price for an animal” here.",
    "home_note_shop_pers_h": "Shop → Custom orders",
    "home_note_shop_pers_p": "Custom design orders (e.g. T-shirts); money goes to the project, not to buying an animal.",
    "home_note_shop_photo_h": "Shop → Photo shop (“buy a photo”)",
    "home_note_shop_photo_p": "You buy a photo/support licence; the amount goes toward NGOs — financial support, not buying an animal.",
    "home_note_mypet_h": "MyPet",
    "home_note_mypet_p": "Your panel if you have an account: own listings, messages, adoptions in progress. Promoting a listing = visibility, not a sale.",
    "home_note_ilove_h": "I Love",
    "home_note_ilove_p": "Animals you marked with a heart, so you can return to them easily.",
    "home_note_pub_h": "Advertising",
    "home_note_pub_p": "Book advertising spaces (e.g. on PDF materials) for your brand or organisation — not for selling animals.",
    "home_note_mag_h": "My shop",
    "home_note_mag_p": "Area for collaborator partners: offers and settings for the partner account.",
    "home_note_account_h": "Account, signup, legal",
    "home_note_account_p_auth": "My account, signup, Contact, Terms and footer policies — for rights, privacy and rules of use.",
    "home_note_account_p_guest": "Sign in, signup, Contact, Terms and footer policies — for rights, privacy and rules of use.",
    "home_note_cta_title": "Help too!",
    "home_note_cta_aria": "Get involved",
    "home_promo_pill": "Promotion",
    # PT
    "pt_title": "Find a friend | EU-ADOPT",
    "pt_meta": "Find a friend – animals for adoption on EU-ADOPT. Filter by preference, open profiles and contact for adoption.",
    "pt_filters": "Filters",
    "pt_filters_dogs": "Dog filters",
    "pt_filters_cats": "Cat filters",
    "pt_filters_other": "Other filters",
    "pt_find_match": "Find my match",
    "pt_find_match_title": "Find your matching soul",
    "pt_help_soul": "Help a soul!",
    "pt_help_soul_title": "Support EU-ADOPT",
    "pt_reset": "Reset filters",
    "pt_search_title": "Find your friend",
    "pt_all": "All",
    "pt_dogs": "Dogs",
    "pt_cats": "Cats",
    "pt_other": "Other",
    "pt_county": "County",
    "pt_country": "Country",
    "pt_region": "Region / county",
    "pt_size": "Size",
    "pt_age": "Age",
    "pt_sex": "Sex",
    "pt_all_opt": "— All —",
    "pt_size_s": "Small",
    "pt_size_m": "Medium",
    "pt_size_l": "Large",
    "pt_sex_m": "MALE",
    "pt_sex_f": "FEMALE",
    "pt_open_filters": "Open filters",
    "pt_collapse_filters": "Collapse filters",
    "pt_ask_about": "Ask about me?",
    "pt_list_aria": "Animal list",
    "pt_see_profile": "View profile {name}",
    "pt_ads_aria": "Ads",
    # Transport
    "transport_title": "Transport | EU-ADOPT",
    "transport_request": "Transport request",
    "transport_submit": "SUBMIT REQUEST",
    "transport_aria": "Transport content",
    "transport_t1_title": "Vet transport – request",
    "transport_t1_intro": "Your request goes to partners; the first to accept gets the details.",
    "transport_want": "I want transport",
    "transport_donate": "Donate to a cause",
    "transport_collapse": "Collapse form",
    "transport_actions_aria": "Transport actions",
    "transport_today": "Transport today",
    "transport_intl": "International transport",
    "transport_intl_tip": "Safe pet transport in-country and across borders, with a dedicated vehicle.",
    "transport_county": "COUNTY",
    "transport_country": "COUNTRY",
    "transport_city": "CITY / PLACE",
    "transport_from": "PICK-UP POINT",
    "transport_to": "DROP-OFF POINT",
    "transport_ph_country": "Choose country",
    "transport_ph_county": "Choose or type the county",
    "transport_ph_city": "Choose the county first",
    "transport_ph_from": "Locality, address or pick-up point",
    "transport_ph_to": "Locality, address or drop-off point",
    "transport_map_pick": "Pick on map",
    "transport_map_pick_title": "Open the map and choose the location",
    "transport_datetime": "DATE AND TIME",
    "transport_cal": "Open calendar",
    "transport_dogs_n": "NO. OF DOGS",
    "transport_route": "ROUTE",
    "transport_route_nat": "National",
    "transport_route_int": "International",
    "transport_urgency": "URGENCY",
    "transport_urg_flex": "No strict deadline",
    "transport_urg_today": "Transport today",
    "transport_urg_24": "24 hours",
    "transport_expand_hub": "Show facilities",
    "transport_collapse_hub": "Hide facilities",
    "transport_t2_1": "International transport",
    "transport_t2_1_tip": "Safe pet transport in-country and across borders, with a dedicated vehicle.",
    "transport_t2_2": "Interior facilities",
    "transport_t2_2_tip": "60 specially fitted places for safe transport.",
    "transport_t2_3": "Ventilation / heat",
    "transport_t2_3_tip": "Air conditioning and heating for a steady temperature on the road.",
    "transport_t2_4": "GPS tracking",
    "transport_t2_4_tip": "Real-time tracking of the route and vehicle location.",
    "transport_t2_5": "VET · Vet assistance",
    "transport_t2_5_tip": "Vet on board or veterinary assistance on request during transport.",
    "transport_t2_6": "Food stops",
    "transport_t2_6_tip": "Regular stops for water, food and rest along the route.",
    "transport_t2_7": "Individual comfort",
    "transport_t2_7_tip": "Each animal has its own crate for safety and calm.",
    "transport_t2_8": "Medical VET",
    "transport_t2_8_tip": "Veterinary equipment and treatment available during the journey.",
    "transport_t2_9": "Grooming VET",
    "transport_t2_9_tip": "Grooming and veterinary care on request during road breaks.",
    "transport_t3_title": "For transport…",
    "transport_t3_aria": "Transport advertising spaces",
    "transport_map_title": "Choose location on the map",
    "transport_map_hint": "Search below or tap the map to place a pin. You can move the pin.",
    "transport_map_search": "Search address",
    "transport_map_search_ph": "Search address, street, locality…",
    "transport_map_cancel": "Cancel",
    "transport_map_ok": "Use this location",
    "transport_adopt_h": "Adoption steps",
    "transport_adopt_p": "Fill in the transport details below. Then tap “Continue adoption request” to return to the profile and send the request to the organisation.",
    "transport_adopt_a": "Continue adoption request",
    # Pet profile
    "pet_back": "BACK TO LIST",
    "pet_share": "SHARE",
    "pet_share_aria": "Share (copy profile link)",
    "pet_title_prefix": "PET PROFILE",
    "pet_promote": "PROMOTE ME",
    "pet_promote_aria": "Promote me",
    "pet_msg_ph": "Write your message to the NGO / owner…",
    "pet_adopt_title": "Adoption request",
    "pet_adopt_msg": "Message (optional)",
    "pet_adopt_msg_ph": "Why do you want to adopt? Do you have a yard, other pets…",
    "pet_adopt_cancel": "Cancel",
    "pet_adopt_send": "Send request",
    "pet_adopt_how": "How will you pick up the animal?",
    "pet_adopt_finish": "Finish adoption request",
    "pet_adopt_close": "Close",
    "pet_adopt_send_full": "Send adoption request",
    "pet_adopt_continue": "Continue",
    "pet_adopt_qr_aria": "Adoption and QR code",
    "pet_link_copied": "Link copied. You can paste it to share.",
    "pet_link_copy_fail": "Could not copy the link.",
    "pet_meta_title": "{name} – Adoption | EU-ADOPT",
    "pet_meta_fallback": "Profile {name} – adoption via EU-ADOPT. Details, location and message to the owner on the platform.",
    "pet_lbl_name": "PET NAME *",
    "pet_lbl_species": "SPECIES",
    "pet_lbl_age": "APPROX. AGE *",
    "pet_lbl_size": "SIZE *",
    "pet_lbl_color": "COLOUR",
    "pet_lbl_sterilized": "NEUTERED / SPAYED",
    "pet_lbl_vaccinated": "VACCINATED",
    "pet_lbl_health_book": "HEALTH BOOKLET",
    "pet_lbl_chip": "CHIP",
    "pet_lbl_chip_rua": "CHIP / RUA",
    "pet_lbl_sex": "SEX",
    "pet_lbl_weight": "WEIGHT (APPROX.)",
    "pet_lbl_county": "COUNTY",
    "pet_lbl_country": "COUNTRY",
    "pet_lbl_region": "REGION / COUNTY",
    "pet_lbl_city": "CITY / PLACE",
    "pet_lbl_medical": "MEDICAL ISSUES",
    "pet_lbl_story": "WHO I AM AND WHERE I'M FROM",
    "pet_lbl_messages": "MESSAGES",
    "pet_species_dog": "Dog",
    "pet_species_cat": "Cat",
    "pet_species_other": "Other animal",
    "pet_choose": "Choose",
    "pet_sex_m": "MALE",
    "pet_sex_f": "FEMALE",
    "pet_msg_own": "This is your listing.",
    "pet_msg_login": "Sign in to send a message.",
    "pet_want_adopt": "I WANT TO ADOPT",
    "pet_traits_h": "Personality",
    "pet_traits_match_h": "Adopter match details",
    "pet_observatii_h": "Notes (details about the animal)",
    "pet_observatii_hint": "Behaviour, care — visible to adopters.",
    "pet_qr_title": "Scan the profile",
    "pet_qr_hint": "Open on your phone",
    "pet_qr_aria": "Profile QR code",
    "pet_qr_alt": "QR code to this profile",
    "pet_adopt_demo_note": "Demo only",
    "pet_adopt_inactive_note": "Inactive during population phase",
    "pet_adopt_state_aria": "Adoption status",
    "pet_adopt_state_free": "Available",
    "pet_adopt_demo_msg": "This animal is for demonstration (DEMO) and cannot be adopted.",
    "pet_adopt_inactive_msg": (
        "The “I want to adopt” button is inactive during the population phase. "
        "Online adoptions open after the official launch."
    ),
    # MyPet / I Love
    "mypet_title": "MyPet | EU-ADOPT",
    "mypet_my_adoptions": "My adoptions",
    "mypet_messages": "Messages",
    "mypet_add": "Add a pet",
    "mypet_search_ph": "Search name or chip/RUA",
    "mypet_search_aria": "Search animals",
    "mypet_dogs": "Dogs",
    "mypet_cats": "Cats",
    "mypet_other": "Other",
    "mypet_photo": "Photo",
    "mypet_age": "Age",
    "mypet_in_progress": "In progress",
    "mypet_sheet": "Sheet %",
    "mypet_views": "Views",
    "mypet_adoption": "Adoption",
    "mypet_promote": "Promote",
    "mypet_cancel": "Cancel",
    "mypet_archive": "Archive",
    "mypet_reply_ph": "Reply here…",
    # Promo A2 order note
    "promo_title": "A2 promotion order | EU-ADOPT",
    "promo_h1": "A2 promotion order note",
    "promo_aria": "A2 promotion order note",
    "promo_prelaunch_banner": "Free — pre-launch stage",
    "promo_prelaunch_max": "maximum 1 promotion per account",
    "promo_pet": "Pet",
    "promo_species": "species",
    "promo_service_lbl": "Included service",
    "promo_service_value": "{imp} appearances in the A2 Home grid, {mins} minutes each · {price}",
    "promo_help": (
        "After payment is activated, the listing joins the A2 central grid rotation (12 cells): "
        "one appearance per cell, in two consecutive waves. "
        "If the platform is busy, delivering the full package may take more than 24 hours — "
        "you still get every appearance, with an email report of date/time and cell number for each one."
    ),
    "promo_total": "Total",
    "promo_total_free": "Free activation during pre-launch.",
    "promo_total_paid": "Payment method is chosen when you complete the order in the cart.",
    "promo_add_cart": "Add to cart",
    "promo_price_free": "Free (pre-launch)",
    "promo_done": "Order completed.",
    "promo_done_qty": "Offers no.",
    "promo_done_period": "Period",
    "promo_exit_pt": "Back to Find a friend",
    "promo_exit_pt_go": "Go to Find a friend",
    "promo_exit_mypet": "Back to MyPet",
    "promo_exit_mypet_go": "Go to MyPet",
    "promo_msg_need_pub": "The listing must be published before promotion.",
    "promo_msg_already_cart": "This listing is already in the cart for A2 promotion.",
    "promo_msg_one_only": "During pre-launch you can activate only one A2 promotion per account.",
    "promo_msg_cart_full": "The cart is full (limit {n}). Remove items if you need space.",
    "promo_msg_added": "A2 promotion added to the cart.",
    "promo_msg_added_free": " Activation is free during pre-launch.",
    "promo_msg_added_pay": " Continue to Checkout to pay and confirm.",
    "promo_cart_title": "A2 promotion · {name} — {price} ({imp} appearances × {mins} min)",
    "ilove_title": "I Love – EU-ADOPT",
    "ilove_empty": "No favourites yet. Tap the heart on a photo to save it here.",
    "ilove_heading": "I Love",
    "ilove_lead": "Your hearted animals.",
    "ilove_hearted": "Hearted",
    "ilove_remove": "Remove from I Love",
    "ilove_add": "Add to I Love",
    "ilove_aria": "I Love — favourites",
    "ilove_messages": "Messages",
    "ilove_unavailable": "Listing unavailable or withdrawn",
    # Account
    "account_title": "My account – EU-ADOPT",
    "account_heading": "My account",
    "account_sheet": "Account profile",
    "account_save": "Save",
    "account_save_profile": "Save profile",
    "account_delete": "Delete account",
    "account_delete_scheduled": "Account deletion scheduled.",
    "account_save_org": "Save NGO/company details",
    "account_save_firm": "Save company details",
    # Site guide + PWA + login modal
    "guide_title": "EU-Adopt guide",
    "guide_close": "Close",
    "guide_ph": "Type your question…",
    "guide_ask": "Question",
    "guide_send": "Send",
    "pwa_aria": "EU-Adopt app on phone",
    "pwa_title": "Phone app: EU-Adopt?",
    "pwa_body": "Want a home-screen icon — opens straight to Home.",
    "pwa_ios": "iPhone: Share → Add to Home Screen",
    "pwa_yes": "Yes",
    "pwa_no": "No",
    "login_modal_title": "Continue adoption",
    "login_modal_body": "To continue, create a free account (takes about 30 seconds).",
    "login_modal_login": "Login",
    "login_modal_register": "Create account",
    "login_modal_close": "Close",
    # Auth / misc
    "signup_title": "Create account | EU-ADOPT",
    "publi": "Ad",
    "publicitate": "Advertising",
}


def eu_ui_label(key: str, **fmt) -> str:
    text = _EN.get(key, "")
    if not text:
        return key
    if fmt:
        try:
            return text.format(**fmt)
        except Exception:
            return text
    return text


def eu_ui_pack() -> dict[str, str]:
    return dict(_EN)
