from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('login/forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('login/reset-password/', views.reset_password_view, name='reset_password'),
    path('signup/alege-tip/', views.signup_choose_type_view, name='signup_choose_type'),
    path('signup/persoana-fizica/', views.signup_pf_view, name='signup_pf'),
    path('signup/verificare-sms/', views.signup_verificare_sms_view, name='signup_verificare_sms'),
    path('signup/retrimite-sms/', views.signup_retrimite_sms_view, name='signup_retrimite_sms'),
    path('signup/persoana-fizica/sms/', views.signup_pf_sms_view, name='signup_pf_sms'),  # alias → signup_verificare_sms
    path('signup/verificare-email/', views.signup_pf_check_email_view, name='signup_pf_check_email'),
    path('signup/retrimite-email/', views.signup_retrimite_email_view, name='signup_retrimite_email'),
    path('signup/check-activation-status/', views.signup_check_activation_status_view, name='signup_check_activation_status'),
    path('signup/complete-login/', views.signup_complete_login_view, name='signup_complete_login'),
    path('signup/verify-email/', views.signup_verify_email_view, name='signup_verify_email'),
    path('signup/organizatie/', views.signup_organizatie_view, name='signup_organizatie'),
    path('signup/colaborator/', views.signup_colaborator_view, name='signup_colaborator'),
    path('cont/', views.account_view, name='account'),
    path('cont/schimbare-user/', views.account_edit_username_view, name='account_edit_username'),
    path('cont/upload-avatar/', views.account_upload_avatar_view, name='account_upload_avatar'),
    path('cont/editeaza/', views.account_edit_view, name='account_edit'),
    path('cont/editeaza/verificare-sms/', views.edit_verificare_sms_view, name='edit_verificare_sms'),
    path('cont/editeaza/verificare-email/', views.edit_check_email_view, name='edit_check_email'),
    path('cont/editeaza/confirmare-email/', views.edit_verify_email_view, name='edit_verify_email'),
    path('admin-analysis/', views.admin_analysis_home_view, name='admin_analysis_home'),
    path('admin-analysis/set-view-as/', views.admin_analysis_set_view_as_view, name='admin_analysis_set_view_as'),
    path('admin-analysis/dogs/', views.admin_analysis_dogs_view, name='admin_analysis_dogs'),
    path('admin-analysis/requests/', views.admin_analysis_requests_view, name='admin_analysis_requests'),
    path('admin-analysis/users/', views.admin_analysis_users_view, name='admin_analysis_users'),
    path('admin-analysis/alerts/', views.admin_analysis_alerts_view, name='admin_analysis_alerts'),
    path('mypet/', views.mypet_view, name='mypet'),
    path('mypet/add/', views.mypet_add_view, name='mypet_add'),
    path('mypet/edit/<int:pk>/', views.mypet_edit_view, name='mypet_edit'),
    path('i-love/', views.i_love_view, name='i_love'),
    path('wishlist/toggle/', views.wishlist_toggle_view, name='wishlist_toggle'),
    path('servicii/', views.servicii_view, name='servicii'),
    path('transport/', views.transport_view, name='transport'),

    path('custi/', views.custi_view, name='custi'),
    path('shop/', views.shop_view, name='shop'),
    path('shop/comanda-personalizate/', views.shop_comanda_personalizate_view, name='shop_comanda_personalizate'),
    path('shop/magazin-foto/', views.shop_magazin_foto_view, name='shop_magazin_foto'),

    path('pets/', views.home_view, name='pets_all'),
    path('pets/<int:pk>/', views.dog_profile_view, name='pets_single'),
    path('pets/<int:pk>/track/', views.pet_track_event_view, name='pet_track_event'),
    path('mypet/observatii/<int:pk>/', views.mypet_observatii_update_view, name='mypet_observatii_update'),
]