"""
Django settings for euadopt_final project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# În producție setează DJANGO_SECRET_KEY în mediu (vezi .env.example). Fallback doar pentru dev local.
_SECRET_FALLBACK = "django-insecure-wu12p^yxl^qac$r@#16ts1c%l23=h$lfz5_v%yqx!8v^8y@q@p"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip() or _SECRET_FALLBACK

# SECURITY WARNING: don't run with debug turned on in production!
# Workflow: DEBUG este controlat doar din env (ex. în `.env`), cu default sigur = False.
_debug_env = os.environ.get("DJANGO_DEBUG", "").strip().lower()
DEBUG = _debug_env in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [
    "eu-adopt.ro",
    "www.eu-adopt.ro",
    ".onrender.com",
    "127.0.0.1",
    "192.168.10.85",
    "192.168.1.15",
    "localhost",
]
# Dev: IP telefon / alt LAN fără edit manual (ex. DJANGO_ALLOWED_HOSTS=192.168.1.100,192.168.0.5)
_extra_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _extra_allowed:
    ALLOWED_HOSTS.extend([h.strip() for h in _extra_allowed.split(",") if h.strip()])
# Rețea Wi-Fi nouă → IP LAN altfel; cu DEBUG=True acceptăm orice Host (doar mediu local).
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("*")

# POST-uri AJAX (ex. coș site-cart) verifică Origin/Referer; listă explicită pentru www/apex și dev local.
CSRF_TRUSTED_ORIGINS = [
    "https://www.eu-adopt.ro",
    "https://eu-adopt.ro",
    "https://*.onrender.com",
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            "http://127.0.0.1:8000",
            "http://127.0.0.1:8001",
            "http://localhost:8000",
            "http://localhost:8001",
        ]
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'home.apps.HomeConfig',
]

# django.contrib.sites – domeniu pentru sitemap URL-uri absolute.
# În producție: Admin → Sites → Site → Domain name = www.eu-adopt.ro (sau setează EUADOPT_SITE_BASE_URL).
# Dacă SITE_BASE_URL e setat, sitemap folosește acel host (vezi home.sitemaps.EuadoptSitemap).
SITE_ID = 1

# „Site în lucru” doar când SITE_PUBLIC e explicit False (ex. pe Render). Dacă lipsește (ex. local), site-ul e normal.
import os as _os
_site_public = _os.environ.get('SITE_PUBLIC', '').strip().lower()
MAINTENANCE_MODE = _site_public in ('0', 'false', 'no', 'nu')

MIDDLEWARE = [
    'euadopt_final.maintenance_middleware.MaintenanceMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'euadopt_final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.wishlist_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'euadopt_final.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Dev/QA: EUADOPT_RELAX_EMAIL_UNIQUE=1 → formularele (signup + cont) nu resping email duplicat.
# În producție NU seta; rămâne False → validare „email deja folosit” ca înainte.
_relax_email = os.environ.get("EUADOPT_RELAX_EMAIL_UNIQUE", "").strip().lower()
EUADOPT_RELAX_EMAIL_UNIQUE = _relax_email in ("1", "true", "yes", "on")

# Cache pentru waiting_id / one-time login (activare din mail pe alt device)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = ['static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fișiere încărcate de utilizatori (ex: poză profil) – URL de la rădăcina site-ului
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Link absolut în emailuri (ex. Accept/Respinge adopție, bonus, remindere).
# Dacă lipsește, multe clienți de mail interpretează href-uri relative ca http:///cale → link invalid.
# În producție (DEBUG=False) folosim fallback la domeniul public dacă env nu e setat.
_EUADOPT_SITE_BASE_URL = os.environ.get("EUADOPT_SITE_BASE_URL", "").strip().rstrip("/")
if _EUADOPT_SITE_BASE_URL:
    SITE_BASE_URL = _EUADOPT_SITE_BASE_URL
elif not DEBUG:
    SITE_BASE_URL = "https://www.eu-adopt.ro"
else:
    # Local: fără env, fallback explicit (sitemap / email); altfel RequestSite în euadopt_sitemap.
    _dev_base = os.environ.get("EUADOPT_SITE_BASE_URL_DEV", "").strip().rstrip("/")
    SITE_BASE_URL = _dev_base or "http://127.0.0.1:8000"

# Google Maps JavaScript API (Places Autocomplete pe /transport/). Setează EUADOPT_GOOGLE_MAPS_API_KEY în .env.
GOOGLE_MAPS_API_KEY = os.environ.get("EUADOPT_GOOGLE_MAPS_API_KEY", "").strip()

# Upload limits (video demo / fișiere MyPet)
# Implicit Django poate bloca request-uri > ~2.5MB (DATA_UPLOAD_MAX_MEMORY_SIZE).
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

# Email – implicit Gmail (SMTP). Parola: „Parolă pentru aplicații” Google.
# Setează EMAIL_HOST_PASSWORD în .env; dacă lipsește → backend consolă (fără inbox real).
_email_password = _os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
_email_user = _os.environ.get("EMAIL_HOST_USER", "").strip() or "euadopt@gmail.com"
EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
    if _email_password
    else "django.core.mail.backends.console.EmailBackend"
)
EMAIL_HOST = _os.environ.get("EMAIL_HOST", "smtp.gmail.com").strip() or "smtp.gmail.com"
try:
    EMAIL_PORT = int((_os.environ.get("EMAIL_PORT", "587") or "587").strip())
except ValueError:
    EMAIL_PORT = 587
EMAIL_USE_TLS = _os.environ.get("EMAIL_USE_TLS", "1").strip().lower() not in ("0", "false", "no")
EMAIL_HOST_USER = _email_user
EMAIL_HOST_PASSWORD = _email_password
DEFAULT_FROM_EMAIL = _os.environ.get("DEFAULT_FROM_EMAIL", "").strip() or _email_user
# Opțional: domeniu FQDN pentru antet Message-ID la emailuri (ex. euadopt.ro). Lasă gol → primul ALLOWED_HOSTS valid.
EMAIL_MESSAGE_ID_DOMAIN = _os.environ.get("EMAIL_MESSAGE_ID_DOMAIN", "").strip() or None

# WhiteNoise + stocare fișiere (Django 6: STORAGES cu cheie "default" pentru upload-uri)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    }
}

# HTTPS / cookie-uri secure — doar când setezi explicit (ex. Render + domeniu real). Local fără variabilă = comportament actual.
if os.environ.get("DJANGO_SECURE_SSL", "").strip().lower() in ("1", "true", "yes", "on"):
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Publicitate — materiale post-plată (formular + email cu token)
PUBLICITATE_CREATIVE_TOKEN_DAYS = int(os.environ.get("PUBLICITATE_CREATIVE_TOKEN_DAYS", "90") or "90")
PUBLICITATE_CREATIVE_REVIEW_HOURS = int(os.environ.get("PUBLICITATE_CREATIVE_REVIEW_HOURS", "12") or "12")
PUBLICITATE_CREATIVE_MAX_UPLOAD_MB = int(os.environ.get("PUBLICITATE_CREATIVE_MAX_UPLOAD_MB", "4") or "4")
# Listă separată prin virgulă pentru notificări „materiale publicitate”. Gol = ADMINS, apoi DEFAULT_FROM_EMAIL (în views).
PUBLICITATE_CREATIVE_STAFF_EMAILS = os.environ.get("PUBLICITATE_CREATIVE_STAFF_EMAILS", "").strip()
# Notificări cereri plată coș site (navbar). Gol = aceeași cascadă ca materiale publicitate în views.
SITE_CART_CHECKOUT_STAFF_EMAILS = os.environ.get("SITE_CART_CHECKOUT_STAFF_EMAILS", "").strip()