"""
Django settings for euadopt_final project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse
from decouple import config
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# În producție setează DJANGO_SECRET_KEY în mediu (vezi .env.example).
# Fallback-ul de mai jos rămâne doar pentru dev local/offline, dar evită forma "django-insecure-*"
# ca să nu declanșeze warning-ul de deploy checklist.
_SECRET_FALLBACK = "euadopt-local-fallback-4Xf9Qm2#rT8vK1!pL6zN3@cH7wS5yD0uJbE"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip() or _SECRET_FALLBACK

# SECURITY WARNING: don't run with debug turned on in production!
# Workflow: DEBUG este controlat doar din env (ex. în `.env`), cu default sigur = False.
_debug_env = os.environ.get("DJANGO_DEBUG", "").strip().lower()
DEBUG = _debug_env in ("1", "true", "yes", "on")

ALLOWED_HOSTS = [
    "eu-adopt.ro",
    "www.eu-adopt.ro",
    ".onrender.com",
    "127.0.0.1",
    "192.168.10.85",
    "192.168.1.15",
    "localhost",
]
# Dev: IP telefon / alt LAN fără edit manual (ex. DJANGO_ALLOWED_HOSTS=192.168.1.100,192.168.0.5)
_extra_allowed = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _extra_allowed:
    ALLOWED_HOSTS.extend([h.strip() for h in _extra_allowed.split(",") if h.strip()])
# Rețea Wi-Fi nouă → IP LAN altfel; cu DEBUG=True acceptăm orice Host (doar mediu local).
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("*")

# POST-uri AJAX (ex. coș site-cart) verifică Origin/Referer; listă explicită pentru www/apex și dev local.
CSRF_TRUSTED_ORIGINS = [
    "https://www.eu-adopt.ro",
    "https://eu-adopt.ro",
    "https://*.onrender.com",
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(
        [
            "http://127.0.0.1:8000",
            "http://127.0.0.1:8001",
            "http://localhost:8000",
            "http://localhost:8001",
        ]
    )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'home.apps.HomeConfig',
]

# django.contrib.sites – domeniu pentru sitemap URL-uri absolute.
# În producție: Admin → Sites → Site → Domain name = www.eu-adopt.ro (sau setează EUADOPT_SITE_BASE_URL).
# Dacă SITE_BASE_URL e setat, sitemap folosește acel host (vezi home.sitemaps.EuadoptSitemap).
SITE_ID = 1

# „Site în lucru” doar când SITE_PUBLIC e explicit False (ex. pe Render). Dacă lipsește (ex. local), site-ul e normal.
import os as _os
_site_public = _os.environ.get('SITE_PUBLIC', '').strip().lower()
MAINTENANCE_MODE = _site_public in ('0', 'false', 'no', 'nu')

# PRE-LAUNCH: site vizibil doar după login (fără înregistrare publică). Dezactivare: EUADOPT_PRELAUNCH_MODE=0
_prelaunch = _os.environ.get("EUADOPT_PRELAUNCH_MODE", "").strip().lower()
PRELAUNCH_MODE = _prelaunch in ("1", "true", "yes", "on")

# Publicitate + promovare A2 gratuite în pre-lansare (1 casetă PUB/cont, 1 promovare/cont, 1 ofertă serviciu/cont).
_pub_free_env = _os.environ.get("EUADOPT_PUBLICITATE_PRELAUNCH_FREE", "").strip().lower()
if _pub_free_env in ("0", "false", "no", "off"):
    PUBLICITATE_PRELAUNCH_FREE = False
elif _pub_free_env in ("1", "true", "yes", "on"):
    PUBLICITATE_PRELAUNCH_FREE = True
else:
    PUBLICITATE_PRELAUNCH_FREE = PRELAUNCH_MODE
PUBLICITATE_PRELAUNCH_MAX_SLOTS_PER_USER = int(_os.environ.get("EUADOPT_PUB_MAX_SLOTS_PER_USER", "1") or "1")
PROMO_A2_PRELAUNCH_MAX_PER_USER = int(_os.environ.get("EUADOPT_PROMO_A2_MAX_PER_USER", "1") or "1")
COLLAB_PRELAUNCH_MAX_OFFERS_PER_USER = int(_os.environ.get("EUADOPT_COLLAB_MAX_OFFERS_PER_USER", "1") or "1")
PROMO_A2_BASE_PRICE_LEI = 10
# Blocare soft Shop / donații / coș comercial în pre-lansare (implicit = PRELAUNCH_MODE). Staff poate testa.
_mon_soft = _os.environ.get("EUADOPT_PRELAUNCH_MONETIZATION_SOFT_LOCK", "").strip().lower()
if _mon_soft in ("0", "false", "no", "off"):
    PRELAUNCH_MONETIZATION_SOFT_LOCK = False
elif _mon_soft in ("1", "true", "yes", "on"):
    PRELAUNCH_MONETIZATION_SOFT_LOCK = True
else:
    PRELAUNCH_MONETIZATION_SOFT_LOCK = PRELAUNCH_MODE

MIDDLEWARE = [
    'euadopt_final.maintenance_middleware.MaintenanceMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'euadopt_final.admin_ip_middleware.AdminIPAllowlistMiddleware',
    'euadopt_final.site_presence_middleware.SitePresenceMiddleware',
    'euadopt_final.login_required_middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'euadopt_final.population_restriction_middleware.PopulationRestrictionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'euadopt_final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.wishlist_counts',
                'home.context_processors.prelaunch_mode',
                'home.context_processors.population_org',
                'home.context_processors.sms_otp',
                'home.context_processors.site_guide',
            ],
        },
    },
]

WSGI_APPLICATION = 'euadopt_final.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _database_from_env():
    raw = (os.environ.get("DATABASE_URL", "") or "").strip()
    if not raw:
        return {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }

    parsed = urlparse(raw)
    scheme = (parsed.scheme or "").lower()
    if scheme in ("postgres", "postgresql"):
        db_cfg = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote((parsed.path or "").lstrip("/")),
            "USER": unquote(parsed.username or ""),
            "PASSWORD": unquote(parsed.password or ""),
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or "5432"),
        }
        if not db_cfg["NAME"]:
            raise RuntimeError("DATABASE_URL is set but database name is missing.")
        q = parse_qs(parsed.query or "")
        sslmode = (q.get("sslmode") or [""])[0].strip()
        if sslmode:
            db_cfg["OPTIONS"] = {"sslmode": sslmode}
        return {"default": db_cfg}

    raise RuntimeError(
        "Unsupported DATABASE_URL scheme. Use postgres:// or postgresql:// for Render PostgreSQL."
    )


DATABASES = _database_from_env()

# Dev/QA: EUADOPT_RELAX_EMAIL_UNIQUE=1 → formularele (signup + cont) nu resping email duplicat.
# În producție NU seta; rămâne False → validare „email deja folosit” ca înainte.
_relax_email = os.environ.get("EUADOPT_RELAX_EMAIL_UNIQUE", "").strip().lower()
EUADOPT_RELAX_EMAIL_UNIQUE = _relax_email in ("1", "true", "yes", "on")

# SMS OTP (înregistrare + schimbare telefon). 0 = cod fix afișat pe ecran, fără trimitere SMS.
_sms_otp_on = os.environ.get("EUADOPT_SMS_OTP_ENABLED", "").strip().lower()
SMS_OTP_ENABLED = _sms_otp_on in ("1", "true", "yes", "on")
EUADOPT_SMSAPI_TOKEN = os.environ.get("EUADOPT_SMSAPI_TOKEN", "").strip()
EUADOPT_SMSAPI_SENDER = os.environ.get("EUADOPT_SMSAPI_SENDER", "EU-Adopt").strip() or "EU-Adopt"
EUADOPT_SMSAPI_API_URL = os.environ.get("EUADOPT_SMSAPI_API_URL", "https://api.smsapi.ro/").strip()
SMS_OTP_DEV_CODE = (os.environ.get("EUADOPT_SMS_OTP_DEV_CODE", "528419").strip() or "528419")[:10]
SMS_OTP_TTL_SECONDS = 300

# Populare adăpost / ONG — min/max animale, meniu redus. Vezi docs/POPULARE_ADAPOST_ONG.md
_population_on = os.environ.get("EUADOPT_POPULATION_ONBOARDING", "").strip().lower()
if _population_on in ("0", "false", "no", "off"):
    POPULATION_ONBOARDING_ENABLED = False
elif _population_on in ("1", "true", "yes", "on"):
    POPULATION_ONBOARDING_ENABLED = True
else:
    POPULATION_ONBOARDING_ENABLED = PRELAUNCH_MODE
POPULATION_ANIMAL_MIN = int(os.environ.get("EUADOPT_POPULATION_ANIMAL_MIN", "2") or "2")
POPULATION_ANIMAL_MAX = int(os.environ.get("EUADOPT_POPULATION_ANIMAL_MAX", "5") or "5")
_population_superuser_only = os.environ.get("EUADOPT_POPULATION_SUPERUSER_ONLY", "").strip().lower()
POPULATION_SUPERUSER_ONLY_LOGIN = _population_superuser_only in ("1", "true", "yes", "on")

# Ghid site (nor FAQ + Gemini fallback opțional). Implicit activ când DEBUG=1.
_site_guide_on = os.environ.get("EUADOPT_SITE_GUIDE_ENABLED", "").strip().lower()
if _site_guide_on in ("0", "false", "no", "off"):
    SITE_GUIDE_ENABLED = False
elif _site_guide_on in ("1", "true", "yes", "on"):
    SITE_GUIDE_ENABLED = True
else:
    SITE_GUIDE_ENABLED = bool(DEBUG)
_site_guide_gemini = os.environ.get("EUADOPT_SITE_GUIDE_GEMINI_ENABLED", "").strip().lower()
SITE_GUIDE_GEMINI_ENABLED = _site_guide_gemini in ("1", "true", "yes", "on")
EUADOPT_GEMINI_API_KEY = os.environ.get("EUADOPT_GEMINI_API_KEY", "").strip()
SITE_GUIDE_GEMINI_MODEL = os.environ.get("EUADOPT_SITE_GUIDE_GEMINI_MODEL", "gemini-2.5-flash").strip()
SITE_GUIDE_RATE_LIMIT_PER_HOUR = int(os.environ.get("EUADOPT_SITE_GUIDE_RATE_LIMIT", "30") or "30")

# Add USER — invitații email prospecte. Implicit DEZACTIVAT (mod tehnic, doar log/simulare).
_invite_mail_on = os.environ.get("EUADOPT_STAFF_INVITE_EMAIL_ENABLED", "").strip().lower()
STAFF_INVITE_EMAIL_ENABLED = _invite_mail_on in ("1", "true", "yes", "on")
STAFF_LEAD_INVITE_COOLDOWN_DAYS = int(os.environ.get("EUADOPT_STAFF_INVITE_COOLDOWN_DAYS", "7") or "7")
STAFF_LEAD_INVITE_LINK_VALID_DAYS = int(os.environ.get("EUADOPT_STAFF_INVITE_LINK_VALID_DAYS", "7") or "7")
STAFF_LEAD_INVITE_MAX_BATCH = 100
STAFF_LEAD_INVITE_MAX_PER_DAY = 30
STAFF_LEAD_INVITE_WAVE_DEFAULT = 20

# Faza C — răspunsuri / bounce (Reply-To invite+{lead_id}@domeniu)
STAFF_INVITE_REPLY_LOCAL = os.environ.get("STAFF_INVITE_REPLY_LOCAL", "invite").strip() or "invite"
STAFF_INVITE_REPLY_TO = os.environ.get("STAFF_INVITE_REPLY_TO", "").strip()
STAFF_INVITE_IMAP_HOST = os.environ.get("STAFF_INVITE_IMAP_HOST", "").strip()
STAFF_INVITE_IMAP_PORT = int(os.environ.get("STAFF_INVITE_IMAP_PORT", "993") or "993")
STAFF_INVITE_IMAP_USER = os.environ.get("STAFF_INVITE_IMAP_USER", "").strip()
STAFF_INVITE_IMAP_PASSWORD = os.environ.get("STAFF_INVITE_IMAP_PASSWORD", "").strip()
STAFF_INVITE_IMAP_FOLDER = os.environ.get("STAFF_INVITE_IMAP_FOLDER", "INBOX").strip() or "INBOX"
STAFF_INVITE_INBOUND_WEBHOOK_SECRET = os.environ.get("STAFF_INVITE_INBOUND_WEBHOOK_SECRET", "").strip()

# Cache: OTP SMS, waiting_id etc. Producție = fișier partajat (Gunicorn are mai mulți workers).
if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": str(BASE_DIR / ".django_cache"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Bucharest'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = ['static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fișiere încărcate de utilizatori (ex: poză profil) – URL de la rădăcina site-ului
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Link absolut în emailuri (ex. Accept/Respinge adopție, bonus, remindere).
# Dacă lipsește, multe clienți de mail interpretează href-uri relative ca http:///cale → link invalid.
# În producție (DEBUG=False) folosim fallback la domeniul public dacă env nu e setat.
_EUADOPT_SITE_BASE_URL = os.environ.get("EUADOPT_SITE_BASE_URL", "").strip().rstrip("/")
if _EUADOPT_SITE_BASE_URL:
    SITE_BASE_URL = _EUADOPT_SITE_BASE_URL
elif not DEBUG:
    SITE_BASE_URL = "https://www.eu-adopt.ro"
else:
    # Local: fără env, fallback explicit (sitemap / email); altfel RequestSite în euadopt_sitemap.
    _dev_base = os.environ.get("EUADOPT_SITE_BASE_URL_DEV", "").strip().rstrip("/")
    SITE_BASE_URL = _dev_base or "http://127.0.0.1:8000"

# DEBUG: același origin ca SITE_BASE_URL (ex. LAN http://192.168.x.x:8000 pentru telefon pe Wi-Fi)
if DEBUG:
    _csrf_site_origin = SITE_BASE_URL.strip().rstrip("/")
    if _csrf_site_origin and _csrf_site_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_csrf_site_origin)

# Google Maps JavaScript API (Places Autocomplete pe /transport/). Setează EUADOPT_GOOGLE_MAPS_API_KEY în .env.
GOOGLE_MAPS_API_KEY = os.environ.get("EUADOPT_GOOGLE_MAPS_API_KEY", "").strip()
# Opțional: cheie separată fără restricție „HTTP referrer” — pentru comenzi server (Places searchText).
GOOGLE_PLACES_SERVER_API_KEY = (
    os.environ.get("EUADOPT_GOOGLE_PLACES_SERVER_API_KEY", "").strip()
    or GOOGLE_MAPS_API_KEY
)

# Upload limits (video demo / fișiere MyPet)
# Implicit Django poate bloca request-uri > ~2.5MB (DATA_UPLOAD_MAX_MEMORY_SIZE).
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

# Email – Zoho Mail (SMTP). Credențiale EXCLUSIV din env (Render / .env local).
# Dacă lipsesc pe Render, aplicația pornește oricum (console backend) — vezi variabilele în .env.example.
_EMAIL_HOST = config("EMAIL_HOST", default="")
_EMAIL_USER = config("EMAIL_HOST_USER", default="")
_EMAIL_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
_EMAIL_CONFIGURED = bool(
    (_EMAIL_HOST or "").strip()
    and (_EMAIL_USER or "").strip()
    and (_EMAIL_PASSWORD or "").strip()
    and (_EMAIL_PASSWORD or "").strip() != "PAROLA_ZOHO_TEMP"
)

if _EMAIL_CONFIGURED:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = _EMAIL_HOST.strip()
    EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=False, cast=bool)
    EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=not EMAIL_USE_TLS, cast=bool)
    if EMAIL_USE_TLS and EMAIL_USE_SSL:
        EMAIL_USE_SSL = False
    _default_port = 587 if EMAIL_USE_TLS else 465
    EMAIL_PORT = config("EMAIL_PORT", default=_default_port, cast=int)
    EMAIL_HOST_USER = _EMAIL_USER.strip()
    EMAIL_HOST_PASSWORD = _EMAIL_PASSWORD
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default=_EMAIL_USER.strip())
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_HOST = ""
    EMAIL_PORT = 587
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = False
    DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="EU-Adopt Team <contact@eu-adopt.ro>")

# Notificări formular Contact (dacă formularul e reactivat)
CONTACT_NOTIFY_EMAIL = (
    _os.environ.get("CONTACT_NOTIFY_EMAIL", "").strip()
    or (_EMAIL_USER.strip() if _EMAIL_CONFIGURED else "")
    or (DEFAULT_FROM_EMAIL or "")
)
# Opțional: domeniu FQDN pentru antet Message-ID la emailuri (ex. euadopt.ro). Lasă gol → primul ALLOWED_HOSTS valid.
EMAIL_MESSAGE_ID_DOMAIN = _os.environ.get("EMAIL_MESSAGE_ID_DOMAIN", "").strip() or None

# WhiteNoise + stocare fișiere (Django 6: STORAGES cu cheie "default" pentru upload-uri)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": MEDIA_ROOT,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    }
}

LOGIN_URL = "/login/"

# HTTPS / cookie-uri secure:
# - implicit ON în producție (DEBUG=False)
# - forțat ON prin DJANGO_SECURE_SSL=1
# - opțional OFF explicit prin DJANGO_SECURE_SSL=0 (strict pentru scenarii locale speciale)
_secure_ssl_env = os.environ.get("DJANGO_SECURE_SSL", "").strip().lower()
_secure_ssl_enabled = (not DEBUG and _secure_ssl_env not in ("0", "false", "no", "off")) or (
    _secure_ssl_env in ("1", "true", "yes", "on")
)
if _secure_ssl_enabled:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # Preload poate fi activat după ce domeniul servește strict HTTPS pe termen lung.
    SECURE_HSTS_PRELOAD = os.environ.get("DJANGO_HSTS_PRELOAD", "1").strip().lower() in ("1", "true", "yes", "on")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Rate-limit autentificare (per IP, cache Django).
AUTH_LOGIN_RATE_LIMIT_PER_15MIN = int(os.environ.get("AUTH_LOGIN_RATE_LIMIT_PER_15MIN", "15") or "15")
AUTH_FORGOT_PASSWORD_RATE_LIMIT_PER_HOUR = int(
    os.environ.get("AUTH_FORGOT_PASSWORD_RATE_LIMIT_PER_HOUR", "5") or "5"
)

# /admin/ — dacă e setat, doar aceste IP-uri (virgulă). Gol = fără restricție suplimentară.
_admin_allow_ip = os.environ.get("EUADOPT_ADMIN_ALLOW_IP", "").strip()
EUADOPT_ADMIN_ALLOW_IPS = [ip.strip() for ip in _admin_allow_ip.split(",") if ip.strip()]

# Publicitate — materiale post-plată (formular + email cu token)
PUBLICITATE_CREATIVE_TOKEN_DAYS = int(os.environ.get("PUBLICITATE_CREATIVE_TOKEN_DAYS", "90") or "90")
PUBLICITATE_CREATIVE_REVIEW_HOURS = int(os.environ.get("PUBLICITATE_CREATIVE_REVIEW_HOURS", "12") or "12")
PUBLICITATE_CREATIVE_MAX_UPLOAD_MB = int(os.environ.get("PUBLICITATE_CREATIVE_MAX_UPLOAD_MB", "4") or "4")
# Listă separată prin virgulă pentru notificări „materiale publicitate”. Gol = ADMINS, apoi DEFAULT_FROM_EMAIL (în views).
PUBLICITATE_CREATIVE_STAFF_EMAILS = os.environ.get("PUBLICITATE_CREATIVE_STAFF_EMAILS", "").strip()
# Notificări cereri plată coș site (navbar). Gol = aceeași cascadă ca materiale publicitate în views.
SITE_CART_CHECKOUT_STAFF_EMAILS = os.environ.get("SITE_CART_CHECKOUT_STAFF_EMAILS", "").strip()