from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from .views import (
    home, pets_all, pets_single, wishlist_view, wishlist_toggle, wishlist_unsubscribe, api_pets_by_ids, pet_ask_view, adoption_form_page, adoption_request_submit, adoption_request_sent, adoption_validate_token_view,
    adoption_finalize_view, adoption_cancel_reservation_view,
    logout_view,
    LoginViewRedirectVerify,
    signup_view, signup_verificare_telefon_view,
    register_choose_type, register_pf, register_organizatie, register_srl, register_ong, register_colaborator,
    contact_view, termeni_view, schema_site_view, transport_view, cages_view, localitati_pe_judet_json_view, ro_counties_cities_json_view, prietenul_tau_v2_view, servicii_view, shop_view,
    site_search_view,
    cont_view, cont_profil_view, cont_ong_view, cont_adauga_animal_view, cont_ong_adauga_view, cont_bulk_add_dogs_view,
    my_posted_pets_view, accept_adoption_request_view,
    beneficii_adoptie_view,
    analiza_view, membri_list_view, analiza_animale_view, analiza_cereri_view,
    debug_send_test_email,
    match_quiz_view, match_results_view,
)

urlpatterns = [
    # HOME: doar home_v2 (template anunturi/home_v2.html); nu mai există home vechi.
    path("", home, name="home"),
    path("index.html", home, name="home_index"),
    path("pets-all.html", pets_all, name="pets_all"),
    path("pet/<int:pk>/", pets_single, name="pets_single"),
    path("wishlist/", wishlist_view, name="wishlist"),
    path("my-wishlist/", RedirectView.as_view(pattern_name="wishlist", permanent=False), name="my_wishlist"),
    path("wishlist/toggle/<int:pk>/", wishlist_toggle, name="wishlist_toggle"),
    path("wishlist/unsubscribe/<str:signed>/", wishlist_unsubscribe, name="wishlist_unsubscribe"),
    path("api/pets-by-ids/", api_pets_by_ids, name="api_pets_by_ids"),
    path("pet/<int:pk>/intreaba/", pet_ask_view, name="pet_ask"),
    path("pet/<int:pk>/adopt/", adoption_form_page, name="adoption_form_page"),
    path("adoption/request/<int:pk>/", adoption_request_submit, name="adoption_request_submit"),
    path("adoption/request/sent/<int:pk>/", adoption_request_sent, name="adoption_request_sent"),
    path("adoption/validate/<str:token>/", adoption_validate_token_view, name="adoption_validate_token"),
    path("adoption/finalize/<int:request_id>/", adoption_finalize_view, name="adoption_finalize"),
    path("adoption/cancel-reservation/<int:request_id>/", adoption_cancel_reservation_view, name="adoption_cancel_reservation"),
    path("pets-single.html", RedirectView.as_view(pattern_name="pets_all", permanent=False), name="pets_single_redirect"),
    # Auth (rute principale)
    path("login/", LoginViewRedirectVerify.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", logout_view, name="logout"),
    path("reset-parola/", auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html", email_template_name="registration/password_reset_email.html", subject_template_name="registration/password_reset_subject.txt", success_url=reverse_lazy("password_reset_done")), name="password_reset"),
    path("reset-parola/trimis/", auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path("reset-parola/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html", success_url=reverse_lazy("password_reset_complete")), name="password_reset_confirm"),
    path("reset-parola/gata/", auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"), name="password_reset_complete"),
    path("register/", register_choose_type, name="register"),
    path("register/pf/", register_pf, name="register_pf"),
    path("register/organizatie/", register_organizatie, name="register_organizatie"),
    path("register/srl/", register_srl, name="register_srl"),
    path("register/ong/", register_ong, name="register_ong"),
    path("register/colaborator/", register_colaborator, name="register_colaborator"),
    # Cont + redirecturi vechi
    path("cont/", cont_view, name="cont"),
    path("cont/login/", RedirectView.as_view(pattern_name="login", permanent=True)),
    path("cont/logout/", RedirectView.as_view(pattern_name="logout", permanent=True)),
    path("cont/inregistrare/", RedirectView.as_view(pattern_name="register", permanent=True)),
    path("cont/verificare-telefon/", signup_verificare_telefon_view, name="signup_verificare_telefon"),
    # Match (Găsește-mi prietenul ideal)
    path("match/quiz/", match_quiz_view, name="match_quiz"),
    path("match/results/", match_results_view, name="match_results"),
    # Pagini statice
    path("transport/", transport_view, name="transport"),
    path("transport/cages/", cages_view, name="cages"),
    path("api/localitati-pe-judet.json", localitati_pe_judet_json_view, name="localitati_pe_judet_json"),
    path("api/ro-counties-cities.json", ro_counties_cities_json_view, name="ro_counties_cities_json"),
    path("prietenele-tau/", prietenul_tau_v2_view, name="prietenul_tau_v2"),
    path("servicii/", servicii_view, name="servicii"),
    path("shop/", shop_view, name="shop"),
    path("contact/", contact_view, name="contact"),
    path("cauta/", site_search_view, name="site_search"),
    path("termeni/", termeni_view, name="termeni"),
    path("schema-site/", schema_site_view, name="schema_site"),
    path("cont/profil/", cont_profil_view, name="cont_profil"),
    path("cont/ong/", cont_ong_view, name="cont_ong"),
    path("cont/adauga-animal/", cont_adauga_animal_view, name="cont_adauga_animal"),
    path("cont/ong/adauga/", cont_ong_adauga_view, name="cont_ong_adauga"),
    path("cont/bulk-add-dogs/", cont_bulk_add_dogs_view, name="cont_bulk_add_dogs"),
    path("my-posted-pets/", my_posted_pets_view, name="my_posted_pets"),
    path("adoption/accept/<int:request_id>/", accept_adoption_request_view, name="adoption_accept_request"),
    path("beneficii-adoptie/", beneficii_adoptie_view, name="beneficii_adoptie"),
    path("analiza/", analiza_view, name="analiza"),
    path("membri/", membri_list_view, name="membri"),
    path("analiza/animale/", analiza_animale_view, name="analiza_animale"),
    path("analiza/cereri/", analiza_cereri_view, name="analiza_cereri"),
    # Temporar: test trimitere email (doar DEBUG sau staff)
    path("debug/send-test-email/", debug_send_test_email, name="debug_send_test_email"),
]


