# Generated by Django 6.0.2 on 2026-02-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome (bun venit)'), ('other', 'Other')], default='welcome', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'SENT'), ('failed', 'FAILED')], max_length=10)),
                ('to_email', models.EmailField(help_text='Adresa la care s-a trimis / a eșuat trimiterea.', max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, help_text='Mesaj eroare dacă status=FAILED.')),
                ('user', models.ForeignKey(blank=True, help_text='Utilizatorul căruia i s-a trimis (sau a eșuat) emailul.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_delivery_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email delivery log',
                'verbose_name_plural': 'Email delivery logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('adopter', 'ADOPTER (PF)'), ('shelter', 'SHELTER (SRL / Adapost)'), ('ong', 'ONG')], default='adopter', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil (accounts)',
                'verbose_name_plural': 'Profili (accounts)',
            },
        ),
    ]
