# Generated by Django 6.0.2 on 2026-02-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildeliverylog',
            name='subject',
            field=models.CharField(blank=True, help_text='Subiectul emailului (opțional).', max_length=255),
        ),
        migrations.AlterField(
            model_name='emaildeliverylog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome (bun venit)'), ('adoption_request_new', 'Cerere nouă adopție'), ('other', 'Other')], default='welcome', max_length=20),
        ),
    ]
