# Generated by Django 6.0.2 on 2026-02-26 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_email_delivery_log_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.CharField(blank=True, choices=[('apartment', 'Apartament'), ('house_no_yard', 'Casă fără curte'), ('house_yard', 'Casă cu curte')], max_length=20)),
                ('experience', models.CharField(blank=True, choices=[('first_dog', 'Primul meu animal'), ('some', 'Am avut în trecut'), ('advanced', 'Experiență multă')], max_length=20)),
                ('activity_level', models.CharField(blank=True, choices=[('low', 'Liniștit'), ('medium', 'Moderat'), ('high', 'Activ')], max_length=20)),
                ('time_available', models.CharField(blank=True, choices=[('low', 'Puțin'), ('normal', 'Moderat'), ('high', 'Mult')], max_length=20)),
                ('has_kids', models.BooleanField(blank=True, null=True)),
                ('has_cat', models.BooleanField(blank=True, null=True)),
                ('has_dog', models.BooleanField(blank=True, null=True)),
                ('size_preference', models.CharField(blank=True, choices=[('small', 'Mic'), ('medium', 'Mediu'), ('large', 'Mare'), ('any', 'Oricare')], max_length=20)),
                ('age_preference', models.CharField(blank=True, choices=[('puppy', 'Pui'), ('adult', 'Adult'), ('senior', 'Senior'), ('any', 'Oricare')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil potrivire (match)',
                'verbose_name_plural': 'Profili potrivire (match)',
            },
        ),
    ]
