# Generated by Django 6.0.2 on 2026-02-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0002_add_tip_altele'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='judet',
            field=models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], help_text='Județul unde se află animalul / adăpostul.', max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tip',
            field=models.CharField(choices=[('dog', 'Câine'), ('cat', 'Pisică'), ('other', 'Altele')], default='dog', max_length=10),
        ),
    ]
