# Generated by Django 6.0.2 on 2026-02-14 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0003_add_judet'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='ong_email',
            field=models.EmailField(blank=True, help_text='Emailul asociației/ONG care are animalul. Primește cererea de adopție după aprobarea voastră.', max_length=254),
        ),
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_complet', models.CharField(max_length=200, verbose_name='Nume complet')),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=30)),
                ('adresa', models.CharField(blank=True, max_length=300)),
                ('mesaj', models.TextField(blank=True, verbose_name='Motivație / alte detalii')),
                ('status', models.CharField(choices=[('new', 'Nouă'), ('approved_platform', 'Aprobată de platformă (trimisă la ONG)'), ('approved_ong', 'Validată de ONG'), ('rejected', 'Refuzată')], default='new', max_length=30)),
                ('data_cerere', models.DateTimeField(auto_now_add=True)),
                ('validation_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='anunturi.pet')),
            ],
            options={
                'verbose_name': 'Cerere adopție',
                'verbose_name_plural': 'Cereri adopție',
                'ordering': ['-data_cerere'],
            },
        ),
    ]
