# Generated by Django 6.0.2 on 2026-02-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0004_adoption_validation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='doreste_cazare_medicala_toiletare',
            field=models.BooleanField(default=False, verbose_name='Dorește cazare medicală cu toiletare'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='doreste_transport',
            field=models.BooleanField(default=False, verbose_name='Dorește transport'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ong_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Adresă ONG'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ong_contact_person',
            field=models.CharField(blank=True, max_length=120, verbose_name='Persoană de contact'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ong_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon ONG'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ong_visiting_hours',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program vizită'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ong_email',
            field=models.EmailField(blank=True, help_text='Emailul asociației. Primește cererea; adoptatorul primește cartea de vizită după validare.', max_length=254),
        ),
    ]
