# Generated by Django 6.0.2 on 2026-02-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0005_ong_card_and_adoption_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='ridicare_personala',
            field=models.BooleanField(default=False, help_text='Clientul vine la adăpost. După aprobare, relația continuă direct între adăpost și client.', verbose_name='Ridicare personală'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='doreste_cazare_medicala_toiletare',
            field=models.BooleanField(default=False, verbose_name='Dorește cazare medicală și toiletare (serviciu platformă)'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='doreste_transport',
            field=models.BooleanField(default=False, verbose_name='Dorește transport la domiciliu (serviciu platformă)'),
        ),
    ]
