# Generated by Django 6.0.2 on 2026-02-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0008_ong_profile_identificare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email contact'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='judet',
            field=models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], help_text='Sediu social – județ (SRL) sau localitate – județ (ONG)', max_length=30, verbose_name='Județ'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='oras',
            field=models.CharField(blank=True, max_length=100, verbose_name='Oraș / Localitate'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='persoana_responsabila_adoptii',
            field=models.CharField(blank=True, max_length=120, verbose_name='Persoană responsabilă adopții'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='reprezentant_legal',
            field=models.CharField(blank=True, max_length=120, verbose_name='Reprezentant legal (opțional)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='telefon',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='tip_organizatie',
            field=models.CharField(choices=[('srl', 'SRL'), ('ong', 'ONG / Asociație')], default='ong', max_length=10, verbose_name='Tip organizație'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='cui',
            field=models.CharField(blank=True, help_text='CUI (SRL) sau CIF (ONG)', max_length=20, verbose_name='CUI / CIF'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='denumire_legala',
            field=models.CharField(blank=True, help_text='Denumire firmă (SRL) sau denumire asociație (ONG)', max_length=200, verbose_name='Denumire'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='numar_registru',
            field=models.CharField(blank=True, help_text='Nr. Registrul Comerțului (J..../..../....) pentru SRL sau nr. registru asociații și fundații pentru ONG', max_length=80, verbose_name='Nr. registru'),
        ),
    ]
