# Generated by Django 6.0.2 on 2026-02-14 22:56

import anunturi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0009_ong_profile_srl_ong_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongprofile',
            name='persoana_responsabila_adoptii',
            field=models.CharField(blank=True, help_text='Obligatoriu: persoana la care apelăm / cu care comunicăm la telefon sau pentru adopții.', max_length=120, verbose_name='Persoană de contact'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='reprezentant_legal',
            field=models.CharField(blank=True, help_text='Obligatoriu pentru SRL: persoana la care apelăm / cu care comunicăm la telefon.', max_length=120, verbose_name='Persoană de contact'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(blank=True, max_length=80, verbose_name='Nume')),
                ('prenume', models.CharField(blank=True, max_length=80, verbose_name='Prenume')),
                ('telefon', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('oras', models.CharField(blank=True, max_length=120, verbose_name='Oraș / Localitate')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('poza_1', models.ImageField(blank=True, help_text='Maxim 3 poze, fiecare max 2 MB.', null=True, upload_to=anunturi.models.user_photo_upload_to, verbose_name='Poza 1')),
                ('poza_2', models.ImageField(blank=True, null=True, upload_to=anunturi.models.user_photo_upload_to, verbose_name='Poza 2')),
                ('poza_3', models.ImageField(blank=True, null=True, upload_to=anunturi.models.user_photo_upload_to, verbose_name='Poza 3')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil persoană fizică',
                'verbose_name_plural': 'Profili persoane fizice',
            },
        ),
    ]
