# Generated by Django 6.0.2 on 2026-02-14 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0010_user_profile_persoana_fizica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Setat după ce utilizatorul introduce codul din SMS.', verbose_name='Telefon verificat prin SMS'),
        ),
        migrations.CreateModel(
            name='SMSVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefon')),
                ('code', models.CharField(max_length=6, verbose_name='Cod 6 cifre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cod verificare SMS',
                'verbose_name_plural': 'Coduri verificare SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
