# Generated by Django 6.0.2 on 2026-02-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0014_pet_added_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ongprofile',
            name='tip_organizatie',
            field=models.CharField(choices=[('srl', 'SRL'), ('ong', 'ONG / Asociație'), ('pfa', 'PFA (persoană fizică autorizată)'), ('af', 'Asociație / Fundație')], default='ong', max_length=10, verbose_name='Tip organizație'),
        ),
    ]
