# Generated by Django 6.0.2 on 2026-02-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0018_alter_adoptionrequest_doreste_cazare_medicala_toiletare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pozitie', models.CharField(choices=[('left', 'Stânga'), ('right', 'Dreapta')], max_length=10, unique=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('url', models.URLField(blank=True, help_text='Unde duce click-ul (lăsați gol pentru #)', max_length=500, verbose_name='Link')),
                ('titlu', models.CharField(blank=True, max_length=120)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Banner header',
                'verbose_name_plural': 'Bannere header',
            },
        ),
        migrations.CreateModel(
            name='ServicesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=80)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Link')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Link servicii',
                'verbose_name_plural': 'Linkuri servicii',
                'ordering': ['ordine', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SliderSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(upload_to='slider/')),
                ('titlu', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True, help_text='Opțional: unde duce click-ul', max_length=500, verbose_name='Link')),
                ('ordine', models.PositiveIntegerField(default=0)),
                ('activ', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Slide slider',
                'verbose_name_plural': 'Slide-uri slider',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
