# Generated by Django 6.0.2 on 2026-02-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0019_add_ads_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='featured',
            field=models.BooleanField(default=False, help_text='Bifează pentru animalele afișate pe prima pagină în secțiunea „Animalele lunii”. Maximum 2 recomandate.', verbose_name='Animale lunii / VIP'),
        ),
    ]
