# Generated by Django 6.0.2 on 2026-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0020_add_pet_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nume', models.CharField(blank=True, max_length=120, verbose_name='Nume (opțional)')),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Destinatar newsletter',
                'verbose_name_plural': 'Destinatari newsletter',
            },
        ),
        migrations.CreateModel(
            name='PresentationEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Subiect email')),
                ('body', models.TextField(help_text='Folosește {{ site_url }} pentru linkul site-ului (ex: http://127.0.0.1:8000).', verbose_name='Corp email (text simplu)')),
                ('activ', models.BooleanField(default=True)),
                ('data_modificare', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template prezentare site',
                'verbose_name_plural': 'Template-uri prezentare',
            },
        ),
        migrations.AlterField(
            model_name='pet',
            name='featured',
            field=models.BooleanField(default=False, help_text='Bifează pentru animalele care plătesc promovare – apar în banda VIP (ticker) de pe prima pagină. Pot fi 10–100+, fiecare reapare la ~3 min.', verbose_name='Zonă VIP (plătit)'),
        ),
    ]
