# Generated by Django 6.0.2 on 2026-02-17 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0022_contest_and_referral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'Persoană fizică'), ('company', 'Persoană juridică (SRL / Firmă)'), ('ngo', 'Asociație / Fundație')], default='individual', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Denumire firmă')),
                ('cui', models.CharField(blank=True, max_length=20, verbose_name='CUI')),
                ('registration_number', models.CharField(blank=True, max_length=80, verbose_name='Nr. registru')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='Persoană de contact')),
                ('organization_name', models.CharField(blank=True, max_length=200, verbose_name='Denumire organizație')),
                ('legal_registration_number', models.CharField(blank=True, max_length=80, verbose_name='Nr. înregistrare')),
                ('representative_name', models.CharField(blank=True, max_length=120, verbose_name='Reprezentant legal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profili',
            },
        ),
    ]
