# Generated by Django 6.0.2 on 2026-02-18 09:38

import anunturi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0023_add_profile_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialTransaction',
        ),
        migrations.DeleteModel(
            name='HeaderBanner',
        ),
        migrations.DeleteModel(
            name='NewsletterRecipient',
        ),
        migrations.DeleteModel(
            name='PresentationEmailTemplate',
        ),
        migrations.DeleteModel(
            name='ServicesLink',
        ),
        migrations.RemoveField(
            model_name='signupverificationfail',
            name='user',
        ),
        migrations.RemoveField(
            model_name='signupverificationlock',
            name='user',
        ),
        migrations.DeleteModel(
            name='SliderSlide',
        ),
        migrations.RemoveField(
            model_name='smsverificationcode',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='referralvisit',
            new_name='anunturi_re_ref_cod_7b18ec_idx',
            old_name='anunturi_re_ref_cod_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='referralvisit',
            new_name='anunturi_re_user_id_609f2b_idx',
            old_name='anunturi_re_user_id_counted_idx',
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='post_adoption_followup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='post_adoption_verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='ridicare_personala',
            field=models.BooleanField(default=False, verbose_name='Ridicare personală, mă deplasez eu la locație'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='prize_image',
            field=models.ImageField(blank=True, null=True, upload_to=anunturi.models.contest_prize_upload_to, verbose_name='Imagine premiu'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='alte_date_identificare',
            field=models.CharField(blank=True, max_length=200, verbose_name='Alte date de identificare'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='cui',
            field=models.CharField(blank=True, max_length=20, verbose_name='CUI / CIF'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='denumire_legala',
            field=models.CharField(blank=True, max_length=200, verbose_name='Denumire'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='judet',
            field=models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], max_length=30, verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='numar_registru',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nr. registru'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='persoana_responsabila_adoptii',
            field=models.CharField(blank=True, max_length=120, verbose_name='Persoană de contact'),
        ),
        migrations.AlterField(
            model_name='ongprofile',
            name='reprezentant_legal',
            field=models.CharField(blank=True, max_length=120, verbose_name='Persoană de contact'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='added_by_user',
            field=models.ForeignKey(blank=True, help_text='Setat când anunțul e adăugat de o persoană fizică.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Animale lunii / VIP'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='ong_email',
            field=models.EmailField(blank=True, help_text='Emailul asociației. Primește cererea.', max_length=254),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('adoptable', 'Adoptable'), ('pending', 'Adoption Pending'), ('adopted', 'Adopted'), ('showcase_archive', 'Showcase Archive')], default='adoptable', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tip_altele',
            field=models.CharField(blank=True, choices=[('bird', 'Pasăre'), ('donkey', 'Magar'), ('rabbit', 'Iepure'), ('hamster', 'Hamster'), ('guinea_pig', 'Cobai'), ('other', 'Altul (completați mai jos)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='tip_altele_altul',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='postadoptionverificationresponse',
            name='mesaj',
            field=models.TextField(blank=True, verbose_name='Cum se simte animalul? Stare, comportament, orice detalii.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Telefon verificat prin SMS'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poza_1',
            field=models.ImageField(blank=True, null=True, upload_to=anunturi.models.user_photo_upload_to, verbose_name='Poza 1'),
        ),
        migrations.DeleteModel(
            name='SignupVerificationFail',
        ),
        migrations.DeleteModel(
            name='SignupVerificationLock',
        ),
        migrations.DeleteModel(
            name='SMSVerificationCode',
        ),
    ]
