# Generated by Django 6.0.2 on 2026-02-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0024_add_showcase_archive_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='imagine_2',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Poză 2'),
        ),
        migrations.AddField(
            model_name='pet',
            name='imagine_3',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Poză 3'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Poză 1 (principală)'),
        ),
    ]
