# Generated by Django 6.0.2 on 2026-02-22 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0027_add_pet_adapost_public_carnet_sanatate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_adopted', models.BooleanField(default=False, help_text='Setat după ce am trimis email că animalul a fost adoptat.')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='anunturi.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Animal preferat',
                'verbose_name_plural': 'Animale preferate',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'pet'), name='unique_user_pet_favorite')],
            },
        ),
    ]
