# Generated by Django 6.0.2 on 2026-02-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0028_add_pet_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='petfavorite',
            name='reminder_72h_sent_at',
            field=models.DateTimeField(blank=True, help_text='Dacă e setat, am trimis deja reminderul „câinii încă disponibili” după 72h.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_informal_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Ultima dată când am trimis emailul informal de mulțumire (la 30 zile).', null=True),
        ),
    ]
