# Generated by Django 6.0.2 on 2026-02-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0029_wishlist_72h_and_informal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_opt_in_wishlist',
            field=models.BooleanField(default=False, help_text='Utilizatorul primește emailuri despre animalele din lista „Te plac” (reminder 72h, adopție, follow-up 30z).', verbose_name='Accept notificări email wishlist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_followup_30d_at',
            field=models.DateTimeField(blank=True, help_text='Data trimiterii emailului „Încă îți cauți prietenul perfect?” (o singură dată / per 30z).', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_wishlist_email_at',
            field=models.DateTimeField(blank=True, help_text='Ultima dată trimiterii unui email wishlist (limită 1 la 7 zile, excepție: email adopție).', null=True),
        ),
    ]
