# Generated by Django 6.0.2 on 2026-02-22 12:23

import anunturi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0030_email_opt_in_wishlist_and_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='judet',
            field=models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], max_length=30, verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='poza_1',
            field=models.ImageField(blank=True, null=True, upload_to=anunturi.models.user_photo_upload_to, verbose_name='Poza (opțional)'),
        ),
    ]
