# Generated by Django 6.0.2 on 2026-02-23 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0031_add_userprofile_judet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Adoptator (cont)'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Proprietar (cine a postat animalul)'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='data_cerere',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data cerere'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='anunturi.pet', verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Refuzată'), ('new', 'Nouă'), ('approved_platform', 'Aprobată de platformă (trimisă la ONG)'), ('approved_ong', 'Validată de ONG')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('adoptable', 'Adoptable'), ('pending', 'În curs de adoptare!'), ('adopted', 'Adopted'), ('showcase_archive', 'Showcase Archive')], default='adoptable', max_length=20),
        ),
    ]
