# Generated by Django 6.0.2 on 2026-02-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0032_add_adoption_request_adopter_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptionrequest',
            options={'ordering': ['data_cerere'], 'verbose_name': 'Cerere adopție', 'verbose_name_plural': 'Cereri adopție'},
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='queue_position',
            field=models.PositiveIntegerField(default=0, help_text='Setat la creare; 1 = primul venit.', verbose_name='Poziție în coadă (1 = primul)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('available', 'Disponibil'), ('reserved', 'În curs de adopție'), ('adopted', 'Adoptat'), ('unavailable', 'Indisponibil')], default='available', max_length=20, verbose_name='Status adopție'),
        ),
        migrations.AddField(
            model_name='pet',
            name='reserved_for_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_pet', to='anunturi.adoptionrequest', verbose_name='Rezervat pentru cererea'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Refuzată'), ('cancelled', 'Anulată'), ('new', 'Nouă'), ('approved_platform', 'Aprobată de platformă (trimisă la ONG)'), ('approved_ong', 'Validată de ONG')], default='pending', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='adoptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('adopter__isnull', False), ('status__in', ['pending', 'approved', 'new', 'approved_platform', 'approved_ong'])), fields=('pet', 'adopter'), name='unique_active_adoption_request_per_pet_adopter'),
        ),
    ]
