# Generated by Django 6.0.2 on 2026-02-23 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0033_adoption_queue_and_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='adoptionrequest',
            name='unique_active_adoption_request_per_pet_adopter',
        ),
        migrations.AddConstraint(
            model_name='adoptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('adopter__isnull', False), ('status__in', ['new', 'approved_ong', 'approved_platform'])), fields=('pet', 'adopter'), name='unique_active_adoption_request_per_pet_adopter'),
        ),
    ]
