# Generated by Django 6.0.2 on 2026-02-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0034_alter_unique_active_adoption_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='varsta_aproximativa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '< 1 an'), (1, '1 an'), (2, '2 ani'), (3, '3 ani'), (4, '4 ani'), (5, '5 ani'), (6, '6 ani'), (7, '7 ani'), (8, '8 ani'), (9, '9 ani'), (10, '10 ani'), (11, '11 ani'), (12, '12 ani'), (13, '13 ani'), (14, '14 ani'), (15, '15 ani'), (16, '> 15 ani')], help_text='Obligatoriu: de la sub 1 an până la peste 15 ani.', null=True, verbose_name='Vârstă aproximativă (ani)'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('rejected', 'Refuzată'), ('cancelled', 'Anulată'), ('rezervat', 'REZERVAT'), ('new', 'Nouă'), ('approved_platform', 'Aprobată de platformă (trimisă la ONG)'), ('approved_ong', 'Validată de ONG')], default='pending', max_length=30),
        ),
    ]
