# Generated by Django 6.0.2 on 2026-02-23 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0038_pet_structured_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adapost_public',
            field=models.BooleanField(default=False, help_text='Bifat doar pentru adăposturi publice. Pentru adăpost public, sterilizat, CIP și carnet sănătate sunt obligatorii. Casutele de mai jos (vaccin, carnet, etc.) pot fi completate de oricine (PF, ONG, adăpost).', verbose_name='Adăpost public'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='marime',
            field=models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], max_length=10, verbose_name='Talie'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='varsta_aproximativa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '< 1 an'), (1, '1 an'), (2, '2 ani'), (3, '3 ani'), (4, '4 ani'), (5, '5 ani'), (6, '6 ani'), (7, '7 ani'), (8, '8 ani'), (9, '9 ani'), (10, '10 ani'), (11, '11 ani'), (12, '12 ani'), (13, '13 ani'), (14, '14 ani'), (15, '15 ani'), (16, '> 15 ani')], null=True, verbose_name='Vârstă aproximativă (ani)'),
        ),
        migrations.AddConstraint(
            model_name='adoptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('adopter__isnull', False)), fields=('pet', 'adopter'), name='unique_pet_adopter_one_per_user'),
        ),
    ]
