# Generated by Django 6.0.2 on 2026-02-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0039_unique_pet_adopter_one_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ongprofile',
            name='adapost_public',
            field=models.BooleanField(default=False, help_text='Bifă obligatorie pentru organizații.', verbose_name='Sunteți adăpost public?'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='legal_country',
            field=models.CharField(blank=True, default='România', max_length=100, verbose_name='Țară (sediu)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='legal_judet',
            field=models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], max_length=30, verbose_name='Județ (sediu)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='legal_locality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localitate (sediu)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='legal_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nr. (sediu)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='legal_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cod poștal (sediu)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='legal_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stradă (sediu)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='pickup_country',
            field=models.CharField(blank=True, default='România', max_length=100, verbose_name='Țară (locație animale)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='pickup_judet',
            field=models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], max_length=30, verbose_name='Județ (locație animale)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='pickup_locality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Localitate (locație animale)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='pickup_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nr. (locație animale)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='pickup_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cod poștal (locație animale, opțional)'),
        ),
        migrations.AddField(
            model_name='ongprofile',
            name='pickup_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stradă (locație animale)'),
        ),
    ]
