# Generated by Django 6.0.2 on 2026-02-23 19:54

import anunturi.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0040_org_legal_pickup_adapost_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume colaborator')),
                ('category', models.CharField(choices=[('vet', 'Cabinet veterinar'), ('grooming', 'Grooming / frizerie'), ('shop', 'Magazin animale')], db_index=True, max_length=20, verbose_name='Categorie')),
                ('county', models.CharField(blank=True, choices=[('alba', 'Alba'), ('arad', 'Arad'), ('arges', 'Argeș'), ('bacau', 'Bacău'), ('bihor', 'Bihor'), ('bistrita-nasaud', 'Bistrița-Năsăud'), ('botosani', 'Botoșani'), ('brasov', 'Brașov'), ('braila', 'Brăila'), ('buzau', 'Buzău'), ('calarasi', 'Călărași'), ('caras-severin', 'Caraș-Severin'), ('cluj', 'Cluj'), ('constanta', 'Constanța'), ('covasna', 'Covasna'), ('dambovita', 'Dâmbovița'), ('dolj', 'Dolj'), ('galati', 'Galați'), ('giurgiu', 'Giurgiu'), ('gorj', 'Gorj'), ('harghita', 'Harghita'), ('hunedoara', 'Hunedoara'), ('ialomita', 'Ialomița'), ('iasi', 'Iași'), ('ilfov', 'Ilfov'), ('maramures', 'Maramureș'), ('mehedinti', 'Mehedinți'), ('mures', 'Mureș'), ('neamt', 'Neamț'), ('olt', 'Olt'), ('prahova', 'Prahova'), ('salaj', 'Sălaj'), ('satu-mare', 'Satu Mare'), ('sibiu', 'Sibiu'), ('suceava', 'Suceava'), ('teleorman', 'Teleorman'), ('timis', 'Timiș'), ('tulcea', 'Tulcea'), ('valcea', 'Vâlcea'), ('vaslui', 'Vaslui'), ('vrancea', 'Vrancea'), ('bucuresti', 'București')], max_length=30, verbose_name='Județ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Localitate')),
                ('offer_text', models.CharField(blank=True, help_text='Ex: -10% la pachet starter', max_length=300, verbose_name='Text ofertă')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=anunturi.models.beneficiary_partner_logo_upload_to, verbose_name='Logo / poză')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email (notificări cupon)')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Link site / pagină')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordine afișare')),
            ],
            options={
                'verbose_name': 'Partener beneficii',
                'verbose_name_plural': 'Parteneri beneficii',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CouponClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vet', 'Cabinet veterinar'), ('grooming', 'Grooming / frizerie'), ('shop', 'Magazin animale')], db_index=True, max_length=20, verbose_name='Categorie')),
                ('status', models.CharField(choices=[('SELECTED', 'Selectat')], default='SELECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data alegere')),
                ('adoption_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_claims', to='anunturi.adoptionrequest', verbose_name='Cerere adopție (opțional)')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='anunturi.beneficiarypartner', verbose_name='Partener')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_claims', to=settings.AUTH_USER_MODEL, verbose_name='Adoptator')),
            ],
            options={
                'verbose_name': 'Alegere cupon',
                'verbose_name_plural': 'Alegeri cupoane',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category'), name='unique_coupon_claim_per_user_category')],
            },
        ),
    ]
