# Generated by Django 6.0.2 on 2026-02-23 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0041_beneficiary_partner_coupon_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data aprobare'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data anulare'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data finalizare'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adoption_requests_finalized', to=settings.AUTH_USER_MODEL, verbose_name='Finalizat de (adăpost)'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobat (așteaptă vizita)'), ('finalized', 'Adopție finalizată'), ('rejected', 'Respins'), ('cancelled', 'Anulat de adoptator'), ('no_show', 'Nu s-a prezentat'), ('waitlist', 'În așteptare (listă)'), ('rezervat', 'REZERVAT'), ('new', 'Nouă'), ('approved_platform', 'Aprobată de platformă (trimisă la ONG)'), ('approved_ong', 'Validată de ONG')], default='pending', max_length=30),
        ),
    ]
