# Generated by Django 6.0.2 on 2026-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0042_adoption_request_timestamps_finalized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_category',
            field=models.CharField(blank=True, choices=[('puppy', 'Pui'), ('young', 'Tânăr'), ('adult', 'Adult'), ('senior', 'Senior')], max_length=20, verbose_name='Categorie vârstă (matching)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='attention_need',
            field=models.CharField(blank=True, choices=[('low', 'Scăzut'), ('medium', 'Mediu'), ('high', 'Ridicat')], max_length=20, verbose_name='Nevoie de atenție'),
        ),
        migrations.AddField(
            model_name='pet',
            name='energy_level',
            field=models.CharField(blank=True, choices=[('low', 'Scăzut'), ('medium', 'Mediu'), ('high', 'Ridicat')], max_length=20, verbose_name='Nivel energie'),
        ),
        migrations.AddField(
            model_name='pet',
            name='experience_required',
            field=models.CharField(blank=True, choices=[('beginner', 'Începător'), ('medium', 'Mediu'), ('experienced', 'Experimentat')], max_length=20, verbose_name='Experiență necesară'),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_cats',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Ok cu pisici'),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_children',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Ok cu copii'),
        ),
        migrations.AddField(
            model_name='pet',
            name='good_with_dogs',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Ok cu câini'),
        ),
        migrations.AddField(
            model_name='pet',
            name='housing_fit',
            field=models.CharField(blank=True, choices=[('apartment', 'Apartament'), ('house', 'Casă'), ('both', 'Ambele')], max_length=20, verbose_name='Potrivit locuință'),
        ),
        migrations.AddField(
            model_name='pet',
            name='size_category',
            field=models.CharField(blank=True, choices=[('small', 'Mic'), ('medium', 'Mediu'), ('large', 'Mare')], max_length=20, verbose_name='Categorie talie (matching)'),
        ),
    ]
