# Generated by Django 6.0.2 on 2026-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0043_add_pet_matching_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='dewormed_status',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('in_progress', 'În curs'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Deparazitat'),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchipped_status',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('in_progress', 'În curs'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Microcipat'),
        ),
        migrations.AddField(
            model_name='pet',
            name='sterilized_status',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('in_progress', 'În curs'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Sterilizat/Castrat'),
        ),
        migrations.AddField(
            model_name='pet',
            name='vaccinated_status',
            field=models.CharField(blank=True, choices=[('yes', 'Da'), ('no', 'Nu'), ('in_progress', 'În curs'), ('unknown', 'Necunoscut')], max_length=20, verbose_name='Vaccinat'),
        ),
        migrations.AddField(
            model_name='pet',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL către un video (YouTube, etc.). Opțional.', max_length=500, verbose_name='Link video (opțional)'),
        ),
    ]
