# Generated by Django 6.0.2 on 2026-02-26 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0044_add_standard_status_and_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Vârstă în ani (0–20). Obligatoriu la postare.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Vârsta (ani)'),
        ),
    ]
