# Generated by Django 6.0.2 on 2026-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0045_add_pet_age_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='ong_pickup_address',
            field=models.CharField(blank=True, help_text='Adresă separată unde se ridică animalul (dacă e diferită de sediul legal).', max_length=300, verbose_name='Locație ridicare câine / locație fizică'),
        ),
    ]
