# Generated by Django 6.0.2 on 2026-03-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_signup_pf_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField(blank=True, null=True, verbose_name='ID animal')),
                ('animal_name', models.CharField(blank=True, max_length=120, verbose_name='Nume animal')),
                ('animal_type', models.CharField(blank=True, max_length=40, verbose_name='Tip animal')),
                ('source', models.CharField(blank=True, help_text='Ex: PT, CUSTI, SHOP, alte surse interne', max_length=40, verbose_name='Sursă')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('approved', 'Aprobată'), ('completed', 'Finalizată'), ('cancelled', 'Anulată')], default='pending', max_length=20, verbose_name='Stare adopție')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Cerere făcută la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adopție utilizator',
                'verbose_name_plural': 'Adopții utilizatori',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('adoption_request', 'Cerere adopție'), ('adoption_story', 'Poveste adopție'), ('donation', 'Donație / campanie'), ('service', 'Serviciu / colaborator'), ('other', 'Alt tip')], default='other', max_length=40, verbose_name='Tip postare')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('body', models.TextField(blank=True, verbose_name='Conținut')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postare utilizator',
                'verbose_name_plural': 'Postări utilizatori',
                'ordering': ['-created_at'],
            },
        ),
    ]
