# Generated by Django 6.0.2 on 2026-03-12 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_account_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nume')),
                ('species', models.CharField(choices=[('dog', 'Câine'), ('cat', 'Pisică'), ('other', 'Alt')], default='dog', max_length=20, verbose_name='Specie')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anunț animal',
                'verbose_name_plural': 'Anunțuri animale',
                'ordering': ['-created_at'],
            },
        ),
    ]
