# Generated by Django 6.0.2 on 2026-03-12 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pf_monthly_animal_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.IntegerField(verbose_name='ID animal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adăugat la')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist item',
                'verbose_name_plural': 'Wishlist items',
                'indexes': [models.Index(fields=['animal_id'], name='home_wishli_animal__84e02c_idx'), models.Index(fields=['user', 'created_at'], name='home_wishli_user_id_91723f_idx')],
                'unique_together': {('user', 'animal_id')},
            },
        ),
    ]
