# Generated by Django 6.0.2 on 2026-03-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='about_pet',
            field=models.TextField(blank=True, verbose_name='Cine sunt și de unde sunt'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='age_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vârstă (eticheta)'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Oraș / Localitate'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='color',
            field=models.CharField(blank=True, max_length=40, verbose_name='Culoare'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='county',
            field=models.CharField(blank=True, max_length=120, verbose_name='Județ'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='has_chip',
            field=models.BooleanField(default=False, verbose_name='CIP'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='has_health_book',
            field=models.BooleanField(default=False, verbose_name='Carnet de sănătate'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='medical_issues',
            field=models.TextField(blank=True, verbose_name='Probleme medicale'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Poză 1'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Poză 2'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='pets/', verbose_name='Poză 3'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talie'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='Sterilizat'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_adapts_easily',
            field=models.BooleanField(default=False, verbose_name='Se adaptează ușor'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_affectionate',
            field=models.BooleanField(default=False, verbose_name='Iubitor'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_apartment_ok',
            field=models.BooleanField(default=False, verbose_name='Potrivit pentru apartament'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_calm',
            field=models.BooleanField(default=False, verbose_name='Liniștit'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_energetic',
            field=models.BooleanField(default=False, verbose_name='Energic'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_good_for_yard',
            field=models.BooleanField(default=False, verbose_name='Bun la curte'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_good_with_cats',
            field=models.BooleanField(default=False, verbose_name='Bun cu pisici'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_good_with_dogs',
            field=models.BooleanField(default=False, verbose_name='Bun cu alți câini'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_good_with_kids',
            field=models.BooleanField(default=False, verbose_name='Bun cu copii'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_house_trained',
            field=models.BooleanField(default=False, verbose_name='Obișnuit în casă'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_leash_trained',
            field=models.BooleanField(default=False, verbose_name='Obișnuit cu lesa'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_low_barker',
            field=models.BooleanField(default=False, verbose_name='Nu latră excesiv'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_needs_experienced_owner',
            field=models.BooleanField(default=False, verbose_name='Necesită experiență cu câini'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_ok_left_alone',
            field=models.BooleanField(default=False, verbose_name='Tolerează să stea singur'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_playful',
            field=models.BooleanField(default=False, verbose_name='Jucăuș'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_protective',
            field=models.BooleanField(default=False, verbose_name='Protector'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='vaccinated',
            field=models.BooleanField(default=False, verbose_name='Vaccinat'),
        ),
    ]
