# Generated by Django 6.0.2 on 2026-03-12 16:51
# Operations removed: schema already applied via 0006_animal_listing_fisa_fields (same model).
# This migration is kept for graph merge only; applying it does nothing (no duplicate columns).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wishlist'),
    ]

    operations = []
