# Generated by Django 6.0.2 on 2026-03-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='age_label',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vârstă (eticheta)'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='carnet_sanatate',
            field=models.CharField(blank=True, max_length=10, verbose_name='Carnet sănătate'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='cine_sunt',
            field=models.TextField(blank=True, verbose_name='Cine sunt și de unde sunt'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='cip',
            field=models.CharField(blank=True, max_length=10, verbose_name='CIP'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Oraș / Localitate'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='color',
            field=models.CharField(blank=True, max_length=80, verbose_name='Culoare'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='county',
            field=models.CharField(blank=True, max_length=120, verbose_name='Județ'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='greutate_aprox',
            field=models.CharField(blank=True, max_length=30, verbose_name='Greutate (aprox.)'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Poza 1'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Poza 2'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Poza 3'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='probleme_medicale',
            field=models.TextField(blank=True, verbose_name='Probleme medicale'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='sex',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sex'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='size',
            field=models.CharField(blank=True, max_length=20, verbose_name='Talie'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='sterilizat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Sterilizat'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_apartament',
            field=models.BooleanField(default=False, verbose_name='Potrivit pentru apartament'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_bun_caini',
            field=models.BooleanField(default=False, verbose_name='Bun cu alți câini'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_bun_copii',
            field=models.BooleanField(default=False, verbose_name='Bun cu copii'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_bun_pisici',
            field=models.BooleanField(default=False, verbose_name='Bun cu pisici'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_energic',
            field=models.BooleanField(default=False, verbose_name='Energetic'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_iubitor',
            field=models.BooleanField(default=False, verbose_name='Iubitor'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_jucaus',
            field=models.BooleanField(default=False, verbose_name='Jucăuș'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_linistit',
            field=models.BooleanField(default=False, verbose_name='Liniștit'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_necesita_experienta',
            field=models.BooleanField(default=False, verbose_name='Necesită experiență cu câini'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_nu_latla',
            field=models.BooleanField(default=False, verbose_name='Nu latră excesiv'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_obisnuit_casa',
            field=models.BooleanField(default=False, verbose_name='Obișnuit în casă'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_obisnuit_lesa',
            field=models.BooleanField(default=False, verbose_name='Obișnuit cu lesa'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_protector',
            field=models.BooleanField(default=False, verbose_name='Protector'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_se_adapteaza',
            field=models.BooleanField(default=False, verbose_name='Se adaptează ușor'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='trait_tolereaza_singur',
            field=models.BooleanField(default=False, verbose_name='Tolerează să stea singur'),
        ),
        migrations.AddField(
            model_name='animallisting',
            name='vaccinat',
            field=models.CharField(blank=True, max_length=10, verbose_name='Vaccinat'),
        ),
    ]
