# Generated by Django 6.0.2 on 2026-03-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_animal_listing_fisa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='judet',
            field=models.CharField(blank=True, max_length=120, verbose_name='Județ'),
        ),
    ]
