# Generated by Django 6.0.2 on 2026-03-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_judet_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='is_public_shelter',
            field=models.BooleanField(default=False, verbose_name='Adăpost public'),
        ),
    ]
