# Generated by Django 6.0.2 on 2026-03-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_animallisting_about_pet_animallisting_age_label_and_more'),
        ('home', '0008_add_is_public_shelter'),
    ]

    operations = [
    ]
