# Generated by Django 6.0.2 on 2026-03-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20260314_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collaborator_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tip colaborator'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adresă firmă'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_cui',
            field=models.CharField(blank=True, max_length=32, verbose_name='CUI/CIF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_cui_has_ro',
            field=models.BooleanField(default=False, verbose_name='CUI cu RO'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_display_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Denumire afișată'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_judet',
            field=models.CharField(blank=True, max_length=120, verbose_name='Județ firmă'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_legal_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Denumire societate'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_oras',
            field=models.CharField(blank=True, max_length=120, verbose_name='Oraș firmă'),
        ),
    ]
