# Generated by Django 6.0.2 on 2026-03-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile_collaborator_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='animals/videos/', verbose_name='Video'),
        ),
    ]
