# Generated by Cursor on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_animallisting_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="animallisting",
            name="media_views",
            field=models.IntegerField(default=0, verbose_name="Vizualizări media (click pe poză/video)"),
        ),
        migrations.AddField(
            model_name="animallisting",
            name="share_clicks",
            field=models.IntegerField(default=0, verbose_name="Distribuiri (click pe buton)"),
        ),
    ]

