# Generated by Cursor on 2026-03-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_animallisting_media_views_share_clicks"),
    ]

    operations = [
        migrations.AddField(
            model_name="animallisting",
            name="observatii",
            field=models.TextField(blank=True, default="", verbose_name="Observații (MyPet)"),
        ),
    ]

