# Generated by Django 6.0.2 on 2026-03-19 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_petmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_asteptare', 'În așteptare (owner)'), ('acceptata', 'Acceptată'), ('respinsa', 'Respinsă'), ('finalizata', 'Adopție finalizată')], default='in_asteptare', max_length=20, verbose_name='Stare')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Acceptată la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cerere adopție',
                'verbose_name_plural': 'Cereri adopție',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='petmessage',
            new_name='home_petmes_animal__6acf4c_idx',
            old_name='pm_animal_created_idx',
        ),
        migrations.RenameIndex(
            model_name='petmessage',
            new_name='home_petmes_receive_500ca8_idx',
            old_name='pm_recv_read_created_idx',
        ),
        migrations.RenameIndex(
            model_name='petmessage',
            new_name='home_petmes_sender__5c4e39_idx',
            old_name='pm_sender_created_idx',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='adopter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_requests', to='home.animallisting'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['animal', 'status'], name='home_adopti_animal__ebab04_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['adopter', 'status'], name='home_adopti_adopter_86147e_idx'),
        ),
    ]
