# Generated by Django 6.0.2 on 2026-03-21 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_adoption_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabServiceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('servicii', 'Servicii'), ('shop', 'Shop'), ('magazin', 'Magazin colaborator'), ('cabinet', 'Cabinet'), ('general', 'General')], default='general', max_length=24, verbose_name='Context')),
                ('context_ref', models.CharField(blank=True, help_text='Opțional: ID/slug când există anunț de serviciu sau produs.', max_length=120, verbose_name='Referință ofertă')),
                ('body', models.TextField(max_length=2000, verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Citit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizat la')),
                ('collaborator', models.ForeignKey(help_text='Colaboratorul (ofertant).', on_delete=django.db.models.deletion.CASCADE, related_name='collab_service_messages_as_collaborator', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_service_messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_service_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesaj servicii / produs',
                'verbose_name_plural': 'Mesaje servicii / produse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collaborator', 'created_at'], name='home_collab_collabo_fe97e6_idx'), models.Index(fields=['collaborator', 'context_type', 'context_ref', 'created_at'], name='home_collab_collabo_8acfe4_idx'), models.Index(fields=['receiver', 'is_read', 'created_at'], name='home_collab_receive_e87b87_idx'), models.Index(fields=['sender', 'created_at'], name='home_collab_sender__c63cc2_idx')],
            },
        ),
    ]
