# Generated by Django 6.0.2 on 2026-03-21 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_collab_service_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titlu serviciu')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Text scurt')),
                ('image', models.ImageField(upload_to='collab_offers/', verbose_name='Imagine')),
                ('price_hint', models.CharField(blank=True, max_length=80, verbose_name='Preț (text scurt)')),
                ('discount_percent', models.PositiveSmallIntegerField(blank=True, help_text='Opțional, 1–100 (ex. 25 pentru 25%).', null=True, verbose_name='Reducere %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activă pe site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ofertă colaborator',
                'verbose_name_plural': 'Oferte colaboratori',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collaborator', 'is_active', 'created_at'], name='home_collab_collabo_5ccfdc_idx')],
            },
        ),
    ]
