# Generated by Django 6.0.2 on 2026-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_collaborator_service_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorserviceoffer',
            name='quantity_available',
            field=models.PositiveIntegerField(blank=True, help_text='Opțional: câte oferte/locuri sunt disponibile (ex. 10).', null=True, verbose_name='Număr oferte valabile'),
        ),
        migrations.AlterField(
            model_name='collaboratorserviceoffer',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Scurtă descriere produs'),
        ),
    ]
