# Generated by Django 6.0.2 on 2026-03-22 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_collaborator_offer_quantity_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorOfferClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Cod ofertă')),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Email cumpărător')),
                ('buyer_name_snapshot', models.CharField(blank=True, max_length=200, verbose_name='Nume (snapshot)')),
                ('buyer_phone_snapshot', models.CharField(blank=True, max_length=40, verbose_name='Telefon (snapshot)')),
                ('buyer_locality_snapshot', models.CharField(blank=True, max_length=200, verbose_name='Localitate (snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collab_offer_claims', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='home.collaboratorserviceoffer')),
            ],
            options={
                'verbose_name': 'Acceptare ofertă colaborator',
                'verbose_name_plural': 'Acceptări oferte colaboratori',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['offer', 'created_at'], name='home_collab_offer_i_364809_idx')],
            },
        ),
    ]
