# Generated by Django 6.0.2 on 2026-03-22 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_collaborator_offer_claim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorserviceoffer',
            name='valid_from',
            field=models.DateField(blank=True, help_text='Prima zi în care oferta e valabilă (calendar România).', null=True, verbose_name='Valabilă de la'),
        ),
        migrations.AddField(
            model_name='collaboratorserviceoffer',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Ultima zi de valabilitate (inclusiv).', null=True, verbose_name='Valabilă până la'),
        ),
        migrations.AddIndex(
            model_name='collaboratorserviceoffer',
            index=models.Index(fields=['is_active', 'valid_until'], name='home_collab_is_acti_5d343a_idx'),
        ),
    ]
