# Generated by Django 6.0.2 on 2026-03-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_promoa2order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collaboratorserviceoffer',
            new_name='home_collab_partner_9435f3_idx',
            old_name='home_collab_partner_7a8b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='promoa2order',
            new_name='home_promoa_status_f580c4_idx',
            old_name='home_promoa_status_202928_idx',
        ),
        migrations.RenameIndex(
            model_name='promoa2order',
            new_name='home_promoa_payer_e_cceda2_idx',
            old_name='home_promoa_payer_e_301f96_idx',
        ),
    ]
