# Generated by Django 6.0.2 on 2026-03-27 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_adoption_states_queue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionBonusSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_kind', models.CharField(choices=[('cabinet', 'Cabinet / clinică veterinară'), ('servicii', 'Servicii / grooming / dresaj'), ('magazin', 'Magazin / pet-shop')], max_length=20, verbose_name='Canal ofertă (snapshot)')),
                ('redemption_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Cod identificare')),
                ('bonus_emails_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Mailuri bonus trimise la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Selecție bonus adopție (ofertă)',
                'verbose_name_plural': 'Selecții bonus adopție',
            },
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='home_contac_topic_22f028_idx',
            old_name='home_contac_topic_5b60f6_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='home_contac_email_bf1897_idx',
            old_name='home_contac_email_651ac3_idx',
        ),
        migrations.RenameIndex(
            model_name='userlegalconsent',
            new_name='home_userle_user_id_cd5389_idx',
            old_name='home_userle_user_id_3965d4_idx',
        ),
        migrations.RenameIndex(
            model_name='userlegalconsent',
            new_name='home_userle_created_554da7_idx',
            old_name='home_userle_created_8da102_idx',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Adopție finalizată la'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='goodwill_email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mail bun venit +15 zile trimis la'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['status', 'goodwill_email_sent_at'], name='home_adopti_status_50927f_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['status', 'finalized_at'], name='home_adopti_status_b3c1cb_idx'),
        ),
        migrations.AddField(
            model_name='adoptionbonusselection',
            name='adoption_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_selections', to='home.adoptionrequest'),
        ),
        migrations.AddField(
            model_name='adoptionbonusselection',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_bonus_selections', to='home.collaboratorserviceoffer'),
        ),
        migrations.AddIndex(
            model_name='adoptionbonusselection',
            index=models.Index(fields=['adoption_request'], name='home_adopti_adoptio_7b56dc_idx'),
        ),
        migrations.AddIndex(
            model_name='adoptionbonusselection',
            index=models.Index(fields=['redemption_code'], name='home_adopti_redempt_7bb23b_idx'),
        ),
        migrations.AddConstraint(
            model_name='adoptionbonusselection',
            constraint=models.UniqueConstraint(fields=('adoption_request', 'partner_kind'), name='uniq_adoption_bonus_per_kind'),
        ),
    ]
