# Generated by Django 6.0.2 on 2026-03-28 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_adoption_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportVeterinaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judet', models.CharField(max_length=120, verbose_name='Județ')),
                ('oras', models.CharField(max_length=120, verbose_name='Oraș / localitate')),
                ('plecare', models.CharField(max_length=500, verbose_name='Punct plecare')),
                ('sosire', models.CharField(max_length=500, verbose_name='Punct sosire')),
                ('plecare_lat', models.CharField(blank=True, default='', max_length=32, verbose_name='Plecare lat')),
                ('plecare_lng', models.CharField(blank=True, default='', max_length=32, verbose_name='Plecare lng')),
                ('sosire_lat', models.CharField(blank=True, default='', max_length=32, verbose_name='Sosire lat')),
                ('sosire_lng', models.CharField(blank=True, default='', max_length=32, verbose_name='Sosire lng')),
                ('data_raw', models.CharField(blank=True, default='', max_length=40, verbose_name='Data (text formular)')),
                ('ora_raw', models.CharField(blank=True, default='', max_length=20, verbose_name='Ora (text formular)')),
                ('nr_caini', models.PositiveSmallIntegerField(default=1, verbose_name='Nr. animale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to='home.animallisting', verbose_name='Anunț asociat (adopție)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_veterinary_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cerere transport veterinar',
                'verbose_name_plural': 'Cereri transport veterinar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_transp_created_b8aad8_idx'), models.Index(fields=['user', '-created_at'], name='home_transp_user_id_133ab7_idx')],
            },
        ),
    ]
