# Generated by Django 6.0.2 on 2026-03-28 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_transport_operator_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportDispatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Deschisă (ofertă)'), ('assigned', 'Asignată'), ('cancelled', 'Anulată'), ('completed', 'Finalizată'), ('expired', 'Expirată'), ('exhausted', 'Fără transportatori disponibili')], db_index=True, default='open', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job dispatch transport',
                'verbose_name_plural': 'Joburi dispatch transport',
            },
        ),
        migrations.CreateModel(
            name='TransportDispatchRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('accepted', 'Acceptat'), ('superseded', 'Luat de altcineva'), ('declined', 'Refuzat')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Destinatar dispatch transport',
                'verbose_name_plural': 'Destinatari dispatch transport',
            },
        ),
        migrations.CreateModel(
            name='TransportTripRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('user_to_op', 'Utilizator → transportator'), ('op_to_user', 'Transportator → utilizator')], max_length=20)),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, default='')),
                ('visible_to_public_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evaluare cursă transport',
                'verbose_name_plural': 'Evaluări cursă transport',
            },
        ),
        migrations.AddField(
            model_name='transportveterinaryrequest',
            name='route_scope',
            field=models.CharField(choices=[('national', 'Național'), ('international', 'Internațional')], default='national', max_length=20, verbose_name='Tip traseu'),
        ),
        migrations.AddField(
            model_name='transportveterinaryrequest',
            name='urgency_window',
            field=models.CharField(choices=[('flex', 'Fără fereastră strictă'), ('today', 'Transport azi'), ('h24', '24 ore')], default='flex', max_length=12, verbose_name='Fereastră timp'),
        ),
        migrations.AddIndex(
            model_name='transportveterinaryrequest',
            index=models.Index(fields=['route_scope', '-created_at'], name='home_transp_route_s_33d12e_idx'),
        ),
        migrations.AddField(
            model_name='transportdispatchjob',
            name='assigned_transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_dispatch_jobs_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transportdispatchjob',
            name='tvr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_job', to='home.transportveterinaryrequest'),
        ),
        migrations.AddField(
            model_name='transportdispatchrecipient',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='home.transportdispatchjob'),
        ),
        migrations.AddField(
            model_name='transportdispatchrecipient',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_dispatch_recipients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporttriprating',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_ratings_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporttriprating',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='home.transportdispatchjob'),
        ),
        migrations.AddField(
            model_name='transporttriprating',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transportdispatchrecipient',
            index=models.Index(fields=['job', 'status'], name='home_transp_job_id_ac0236_idx'),
        ),
        migrations.AddIndex(
            model_name='transportdispatchrecipient',
            index=models.Index(fields=['transporter', 'status'], name='home_transp_transpo_c84bf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transportdispatchrecipient',
            unique_together={('job', 'transporter')},
        ),
        migrations.AddIndex(
            model_name='transporttriprating',
            index=models.Index(fields=['job', 'direction'], name='home_transp_job_id_735385_idx'),
        ),
        migrations.AddIndex(
            model_name='transporttriprating',
            index=models.Index(fields=['to_user', '-created_at'], name='home_transp_to_user_23f9af_idx'),
        ),
    ]
