# Generated by Django 6.0.2 on 2026-03-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_transport_dispatch_and_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='animallisting',
            name='detalii_animal',
            field=models.TextField(blank=True, default='', help_text='Comportament, obiceiuri, ce îi place — vizibil adoptatorilor pe fișă.', verbose_name='Detalii despre animal'),
        ),
    ]
