# Generated by Django 6.0.2 on 2026-04-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_animallisting_detalii_animal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicitateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'În așteptare plată'), ('paid', 'Plătită'), ('cancelled', 'Anulată')], db_index=True, default='pending_payment', max_length=24, verbose_name='Status')),
                ('total_lei', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (lei)')),
                ('payment_provider', models.CharField(default='demo', help_text='demo = simulare; înlocuiește cu stripe/netopia/etc. la go-live.', max_length=32, verbose_name='Procesator plată')),
                ('payment_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='Referință plată')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Plătit la')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicitate_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comandă publicitate',
                'verbose_name_plural': 'Comenzi publicitate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicitateOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=30, verbose_name='Secțiune')),
                ('slot_code', models.CharField(db_index=True, max_length=30, verbose_name='Cod slot')),
                ('title_snapshot', models.CharField(max_length=220, verbose_name='Titlu (snapshot)')),
                ('unit_label', models.CharField(max_length=32, verbose_name='Unitate')),
                ('unit_price_lei', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preț unitar')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Cantitate (luni/ore)')),
                ('line_total_lei', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal linie')),
                ('buyer_note', models.TextField(blank=True, default='', verbose_name='Notă / creative (text sau JSON)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='home.publicitateorder')),
            ],
            options={
                'verbose_name': 'Linie comandă publicitate',
                'verbose_name_plural': 'Linii comandă publicitate',
                'ordering': ['id'],
            },
        ),
    ]
