# Generated by Django 6.0.2 on 2026-04-24 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_user_inbox_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sitecartitem',
            new_name='home_siteca_user_id_700c7a_idx',
            old_name='home_sitecar_user_id_2b8f1e_idx',
        ),
        migrations.RenameIndex(
            model_name='userinboxnotification',
            new_name='home_userin_user_id_d18eec_idx',
            old_name='home_userin_user_id_7a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='userinboxnotification',
            new_name='home_userin_user_id_5cc40a_idx',
            old_name='home_userin_user_id_8d3e4f_idx',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='bonus_servicii_locked_at',
            field=models.DateTimeField(blank=True, help_text='După „Salvează alegerile” pe pagina Servicii: ofertele bonus nu mai pot fi modificate până la decizia proprietarului.', null=True, verbose_name='Bonus Servicii — alegeri salvate la'),
        ),
        migrations.AddIndex(
            model_name='adoptionrequest',
            index=models.Index(fields=['adopter', 'bonus_servicii_locked_at'], name='home_adopti_adopter_8e820f_idx'),
        ),
    ]
