# Generated by Django 6.0.2 on 2026-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_adoption_request_bonus_servicii_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='owner_reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, help_text='Setat când s-a trimis emailul de reamintire la 24h pentru cerere în așteptare.', null=True, verbose_name='Reminder 24h proprietar trimis la'),
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='owner_reminder_72h_sent_at',
            field=models.DateTimeField(blank=True, help_text='Setat când s-a trimis emailul de reamintire la 72h pentru cerere în așteptare.', null=True, verbose_name='Reminder 72h proprietar trimis la'),
        ),
    ]
