# Generated by Django 6.0.2 on 2026-04-29 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_publicitatelinecreative_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoa2order',
            name='activation_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Activare plată'),
        ),
        migrations.AddField(
            model_name='promoa2order',
            name='fulfillment_report_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Raport apariții A2 trimis la'),
        ),
        migrations.AlterField(
            model_name='promoa2order',
            name='package',
            field=models.CharField(choices=[('a2_24', 'A2 — 24 apariții × 5 minute (10 lei)'), ('6h', '6h (legacy)'), ('12h', '12h (legacy)')], default='a2_24', max_length=16, verbose_name='Pachet'),
        ),
        migrations.AlterField(
            model_name='promoa2order',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data start'),
        ),
        migrations.AlterField(
            model_name='sitecartitem',
            name='kind',
            field=models.CharField(choices=[('servicii_offer', 'Ofertă Servicii'), ('shop', 'Shop'), ('shop_custom', 'Shop produse personalizate'), ('shop_foto', 'Magazin foto'), ('publicitate', 'Publicitate'), ('promo_a2', 'Promovare animal (A2 / MyPet)')], max_length=32),
        ),
        migrations.CreateModel(
            name='PromoA2SlotPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Index apariție 1–24')),
                ('cell_index', models.PositiveSmallIntegerField(verbose_name='Casetă A2 (1–12)')),
                ('window_start', models.DateTimeField(verbose_name='Început fereastră')),
                ('window_end', models.DateTimeField(verbose_name='Sfârșit fereastră')),
                ('logged_at', models.DateTimeField(blank=True, null=True, verbose_name='Înregistrată (vizualizare sau backfill)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_plans', to='home.promoa2order')),
            ],
            options={
                'verbose_name': 'Slot Promo A2',
                'verbose_name_plural': 'Sloturi Promo A2',
                'ordering': ['order_id', 'sequence'],
                'indexes': [models.Index(fields=['window_start', 'window_end'], name='home_promoa_window__b9c814_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'sequence'), name='uniq_promoa2_slot_order_seq')],
            },
        ),
    ]
