# Generated by Django 6.0.2 on 2026-05-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_userprofile_donation_fiscal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='pending_deletion_finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ștergere/anonymizare finalizată la'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='pending_deletion_grace_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ștergere finală după (sfârșit grație)'),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='pending_deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cerere ștergere la'),
        ),
    ]
