# Generated by Django 6.0.2 on 2026-05-12 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_accountprofile_pending_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffOnboardingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon')),
                ('display_name', models.CharField(max_length=200, verbose_name='Nume afișat / persoană contact')),
                ('org_display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Denumire organizație (ONG/adăpost)')),
                ('account_kind', models.CharField(choices=[('pf', 'Persoană fizică'), ('org', 'ONG / Asociație / Adăpost'), ('collaborator', 'Colaborator')], db_index=True, max_length=20, verbose_name='Rol în site (țintă)')),
                ('collaborator_subtype', models.CharField(blank=True, choices=[('', '—'), ('cabinet', 'Cabinet veterinar'), ('servicii', 'Servicii (altele)'), ('magazin', 'Magazin / grooming'), ('transport', 'Transportator')], default='', max_length=20, verbose_name='Tip colaborator')),
                ('judet', models.CharField(blank=True, default='', max_length=120, verbose_name='Județ')),
                ('oras', models.CharField(blank=True, default='', max_length=120, verbose_name='Oraș / localitate')),
                ('segments', models.JSONField(blank=True, default=list, verbose_name='Segmente / categorii mail')),
                ('marketing_emails_requested', models.BooleanField(default=False, verbose_name='Include în viitoare mailuri (după confirmare dublă / bifă pe site)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Pregătit'), ('invited', 'Invitație trimisă'), ('consented', 'Consimțăminte confirmate'), ('imported', 'Importat ca utilizator'), ('archived', 'Arhivat')], db_index=True, default='ready', max_length=20)),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notițe staff')),
                ('consent_invite_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('consent_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='Accept termeni (confirmare)')),
                ('consent_privacy_at', models.DateTimeField(blank=True, null=True, verbose_name='Accept GDPR (confirmare)')),
                ('consent_marketing_at', models.DateTimeField(blank=True, null=True, verbose_name='Accept marketing (confirmare)')),
                ('legal_docs_version', models.CharField(blank=True, default='', max_length=20, verbose_name='Versiune documente la confirmare')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_onboarding_leads_created', to=settings.AUTH_USER_MODEL)),
                ('imported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_onboarding_lead_source', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead onboarding (staff)',
                'verbose_name_plural': 'Lead-uri onboarding (staff)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='home_staffo_created_29663a_idx'), models.Index(fields=['account_kind', 'status'], name='home_staffo_account_22116c_idx')],
            },
        ),
    ]
