# Generated by Django 6.0.2 on 2026-05-12 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_staff_onboarding_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresă firmă'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_cui',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='CUI/CIF'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_cui_has_ro',
            field=models.BooleanField(default=False, verbose_name='CUI cu RO'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_judet',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Județ firmă'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_legal_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Denumire legală firmă / ONG'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_oras',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Oraș firmă'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_reg_com',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Nr. Reg. Com. / J'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='company_representative',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Reprezentant legal'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Prenume'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='is_public_shelter',
            field=models.BooleanField(default=False, verbose_name='Adăpost public (ONG)'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nume'),
        ),
        migrations.AddField(
            model_name='staffonboardinglead',
            name='username_suggested',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Username propus (login)'),
        ),
        migrations.AddIndex(
            model_name='staffonboardinglead',
            index=models.Index(fields=['judet', 'oras'], name='home_staffo_judet_8c213b_idx'),
        ),
    ]
