# Generated by Django 6.0.2 on 2026-05-12 19:33

from django.db import migrations, models


def forwards_cmvro_leads_tip(apps, schema_editor):
    StaffOnboardingLead = apps.get_model("home", "StaffOnboardingLead")
    StaffOnboardingLead.objects.filter(notes__icontains="cmvro.cmvro.ro").update(
        account_kind="collaborator",
        collaborator_subtype="cv",
    )


def backwards_cmvro_leads_tip(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_staffonboardinglead_invite_email_last_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffonboardinglead',
            name='collaborator_subtype',
            field=models.CharField(blank=True, choices=[('', '—'), ('cabinet', 'Cabinet veterinar'), ('cv', 'CV'), ('servicii', 'Servicii (altele)'), ('magazin', 'Magazin / grooming'), ('transport', 'Transportator')], default='', max_length=20, verbose_name='Tip colaborator'),
        ),
        migrations.RunPython(forwards_cmvro_leads_tip, backwards_cmvro_leads_tip),
    ]
