# Generated by Django 6.0.2 on 2026-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_staffonboardinglead_collab_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffonboardinglead',
            name='account_kind',
            field=models.CharField(choices=[('pf', 'Persoană fizică'), ('org', 'ONG / Asociație / Adăpost'), ('collaborator', 'Colaborator'), ('adapost', 'Adăpost')], db_index=True, max_length=20, verbose_name='Rol în site (țintă)'),
        ),
        migrations.AlterField(
            model_name='staffonboardinglead',
            name='collaborator_subtype',
            field=models.CharField(blank=True, choices=[('', '—'), ('cabinet', 'Cabinet veterinar'), ('cv', 'CV'), ('servicii', 'Servicii (altele)'), ('magazin', 'Magazin / grooming'), ('transport', 'Transportator'), ('adpub', 'ADPUB'), ('adprv', 'ADPRV')], default='', max_length=20, verbose_name='Tip colaborator'),
        ),
    ]
