# Generated by Django 6.0.2 on 2026-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_staff_lead_adapost_adpub_adprv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffonboardinglead',
            name='collaborator_subtype',
            field=models.CharField(blank=True, choices=[('', '—'), ('cabinet', 'Cabinet veterinar'), ('cv', 'CV'), ('servicii', 'Servicii (altele)'), ('magazin', 'Magazin'), ('grooming', 'Grooming'), ('transport', 'Transportator'), ('adpub', 'ADPUB'), ('adprv', 'ADPRV')], default='', max_length=20, verbose_name='Tip colaborator'),
        ),
    ]
