# Generated by Django 6.0.2 on 2026-05-22 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_staffonboardinglead_vet_prospect_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorofferclaim',
            name='partner_location_adresa_snapshot',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Adresă punct (snapshot)'),
        ),
        migrations.AddField(
            model_name='collaboratorofferclaim',
            name='partner_location_judet_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Județ punct (snapshot)'),
        ),
        migrations.AddField(
            model_name='collaboratorofferclaim',
            name='partner_location_label_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Punct partener (snapshot)'),
        ),
        migrations.AddField(
            model_name='collaboratorofferclaim',
            name='partner_location_oras_snapshot',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Oraș punct (snapshot)'),
        ),
        migrations.CreateModel(
            name='PartnerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text='Ex.: Magazin Roman, Cabinet Piatra Neamț', max_length=120, verbose_name='Denumire punct')),
                ('judet', models.CharField(max_length=120, verbose_name='Județ')),
                ('oras', models.CharField(max_length=120, verbose_name='Oraș / localitate')),
                ('adresa', models.CharField(blank=True, default='', max_length=255, verbose_name='Adresă')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon punct')),
                ('kind', models.CharField(blank=True, choices=[('magazin', 'Magazin / pet-shop'), ('cabinet', 'Cabinet / clinică'), ('servicii', 'Servicii / grooming / dresaj'), ('grooming', 'Grooming'), ('altele', 'Altele')], default='', max_length=20, verbose_name='Tip punct')),
                ('is_sediu_social', models.BooleanField(default=False, help_text='Adresa din acte; un singur sediu per cont.', verbose_name='Sediu social (legal)')),
                ('is_primary', models.BooleanField(default=False, help_text='Primul punct operațional la înregistrare.', verbose_name='Punct principal')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punct de lucru partener',
                'verbose_name_plural': 'Puncte de lucru partener',
                'ordering': ['-is_primary', '-is_sediu_social', 'judet', 'oras', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='collaboratorserviceoffer',
            name='partner_location',
            field=models.ForeignKey(blank=True, help_text='Locația la care se aplică oferta (filtru județ Servicii, emailuri).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_offers', to='home.partnerlocation', verbose_name='Punct de lucru'),
        ),
        migrations.AddIndex(
            model_name='partnerlocation',
            index=models.Index(fields=['user', 'is_active'], name='home_partne_user_id_d4a75c_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerlocation',
            index=models.Index(fields=['judet', 'oras'], name='home_partne_judet_6f02f4_idx'),
        ),
    ]
