# Generated by Django 6.0.6 on 2026-08-25 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0087_lostfoundanimal_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judet', models.CharField(db_index=True, max_length=64, verbose_name='Județ')),
                ('judet_slug', models.CharField(db_index=True, max_length=80, verbose_name='Slug județ')),
                ('judet_code', models.CharField(blank=True, default='', max_length=4, verbose_name='Cod județ')),
                ('destinatie', models.CharField(choices=[('dsvsa', 'DSVSA'), ('bpa', 'Poliția Animalelor (BPA)'), ('both', 'Ambele')], max_length=12, verbose_name='Destinație')),
                ('description', models.TextField(max_length=4000, verbose_name='Problema reclamată')),
                ('media', models.FileField(blank=True, null=True, upload_to='abuz/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'mp4', 'mov', 'webm', 'm4v'])], verbose_name='Poză / video')),
                ('reporter_name', models.CharField(max_length=200, verbose_name='Nume sesizor')),
                ('reporter_email', models.EmailField(max_length=254, verbose_name='Email sesizor')),
                ('reporter_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefon sesizor')),
                ('status', models.CharField(choices=[('queued', 'În așteptare'), ('sent', 'Trimis'), ('partial', 'Parțial trimis'), ('pending_contact', 'Fără contact organ — în așteptare'), ('failed', 'Eșuat')], db_index=True, default='queued', max_length=20, verbose_name='Status trimitere')),
                ('sent_to', models.TextField(blank=True, default='', verbose_name='Destinatari (emailuri)')),
                ('send_log', models.TextField(blank=True, default='', verbose_name='Jurnal trimitere')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sesizare abuz',
                'verbose_name_plural': 'Sesizări abuz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='campaniesterilizare',
            new_name='home_campan_judet_s_4e8b76_idx',
            old_name='home_campan_judet_s_7c1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='campaniesterilizare',
            new_name='home_campan_date_en_223f3f_idx',
            old_name='home_campan_date_en_8d3e4f_idx',
        ),
        migrations.RenameIndex(
            model_name='facebookoutbounddelivery',
            new_name='home_facebo_status_350398_idx',
            old_name='home_fb_del_status_mkt_idx',
        ),
        migrations.RenameIndex(
            model_name='facebookoutbounddelivery',
            new_name='home_facebo_faceboo_a9aeea_idx',
            old_name='home_fb_del_fbpost_idx',
        ),
        migrations.RenameIndex(
            model_name='facebookoutboundpost',
            new_name='home_facebo_status_dc5d49_idx',
            old_name='home_facebo_status_c8a2c1_idx',
        ),
        migrations.RenameIndex(
            model_name='facebookoutboundpost',
            new_name='home_facebo_posted__12c895_idx',
            old_name='home_facebo_posted__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='facebookroinboundpost',
            new_name='home_facebo_status_1ccf1d_idx',
            old_name='home_fb_ro_in_status_idx',
        ),
        migrations.RenameIndex(
            model_name='siteloginevent',
            new_name='home_sitelo_logged__83d35f_idx',
            old_name='home_sitelo_logged__a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='siteloginevent',
            new_name='home_sitelo_user_id_d28fd8_idx',
            old_name='home_sitelo_user_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='sitepresenceactive',
            new_name='home_sitepr_last_se_9bc93d_idx',
            old_name='home_site_p_last_seen_idx',
        ),
        migrations.RenameIndex(
            model_name='sitepresenceactive',
            new_name='home_sitepr_last_se_9701ae_idx',
            old_name='home_site_p_seen_user_idx',
        ),
        migrations.RenameIndex(
            model_name='sitepresencedaysession',
            new_name='home_sitepr_day_47a486_idx',
            old_name='home_site_p_day_sess_idx',
        ),
        migrations.RenameIndex(
            model_name='staffonboardinginvitelog',
            new_name='home_staffo_lead_id_63a16c_idx',
            old_name='home_staff_inv_lead_sent',
        ),
        migrations.RenameIndex(
            model_name='userpageonboardingseen',
            new_name='home_userpa_user_id_2a7d0e_idx',
            old_name='home_userpa_user_id_6f2a1c_idx',
        ),
        migrations.AlterField(
            model_name='staffonboardinglead',
            name='invite_cooldown_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Gol = folosește setarea globală (implicit 7 zile).', null=True, verbose_name='Cooldown retrimitere (zile)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='link_extern',
            field=models.CharField(blank=True, default='', help_text='URL opțional (site, Facebook, etc.) — Cont DATE FIRMĂ + Despre noi public.', max_length=500, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='abusereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='abusereport',
            index=models.Index(fields=['judet_slug', '-created_at'], name='home_abuser_judet_s_ff4a98_idx'),
        ),
        migrations.AddIndex(
            model_name='abusereport',
            index=models.Index(fields=['status', '-created_at'], name='home_abuser_status_0fcba1_idx'),
        ),
    ]
