# Generated by Django 6.0.6 on 2026-08-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_abuse_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='abusereport',
            name='gdpr_accepted',
            field=models.BooleanField(default=False, verbose_name='Acord GDPR'),
        ),
        migrations.AddField(
            model_name='abusereport',
            name='incident_location',
            field=models.CharField(blank=True, default='', help_text='Localitate, adresă, puncte de reper', max_length=255, verbose_name='Locația faptei'),
        ),
        migrations.AddField(
            model_name='abusereport',
            name='incident_when',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Data / ora aproximativă'),
        ),
        migrations.AddField(
            model_name='abusereport',
            name='reporter_domicile',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Domiciliu sesizor'),
        ),
    ]
