# Generated by Django 6.0.2 on 2026-02-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('rasa', models.CharField(max_length=100)),
                ('tip', models.CharField(choices=[('dog', 'Câine'), ('cat', 'Pisică')], default='dog', max_length=10)),
                ('varsta', models.CharField(choices=[('baby', 'Baby'), ('young', 'Young'), ('adult', 'Adult')], max_length=10)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('marime', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Extra Large')], max_length=10)),
                ('descriere', models.TextField(blank=True)),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('imagine_fallback', models.CharField(blank=True, help_text='Path static ex: images/pets/charlie-275x275.jpg dacă nu e upload', max_length=200)),
                ('status', models.CharField(choices=[('adoptable', 'Adoptable'), ('pending', 'Adoption Pending'), ('adopted', 'Adopted')], default='adoptable', max_length=20)),
                ('tags', models.TextField(blank=True, help_text='Separate prin virgulă: Adoptable, Spayed/Neutered, House trained')),
                ('data_adaugare', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animale',
                'ordering': ['-data_adaugare'],
            },
        ),
    ]
