# Generated by Django 6.0.2 on 2026-02-14 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0007_user_groups_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OngProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cui', models.CharField(blank=True, help_text='Cod Unic de Identificare fiscală', max_length=20, verbose_name='CUI')),
                ('denumire_legala', models.CharField(blank=True, help_text='Numele legal al asociației sau adăpostului', max_length=200, verbose_name='Denumire legală')),
                ('numar_registru', models.CharField(blank=True, help_text='Număr registru comerț, ONG sau alte identificare (ex: Ro)', max_length=50, verbose_name='Nr. registru / Ro')),
                ('alte_date_identificare', models.CharField(blank=True, help_text='Alte coduri sau date unice fiscale, dacă e cazul', max_length=200, verbose_name='Alte date de identificare')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ong_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil ONG / Adăpost',
                'verbose_name_plural': 'Profili ONG / Adăposturi',
            },
        ),
    ]
