# Generated by Django 6.0.2 on 2026-02-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0011_sms_verification_and_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='post_adoption_followup_sent_at',
            field=models.DateTimeField(blank=True, help_text='Data la care am trimis emailul de follow-up (soarta animalului) la 3/6 luni.', null=True),
        ),
    ]
