# Generated by Django 6.0.2 on 2026-02-14 23:26

import anunturi.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0012_post_adoption_followup_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='post_adoption_verification_token',
            field=models.CharField(blank=True, help_text='Token din linkul trimis adoptatorului pentru formularul de verificare post-adopție.', max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PostAdoptionVerificationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_raspuns', models.DateTimeField(auto_now_add=True, verbose_name='Data răspuns')),
                ('mesaj', models.TextField(blank=True, help_text='Câteva cuvinte despre soarta animalului.', verbose_name='Cum se simte animalul? Stare, comportament, orice detalii.')),
                ('poza_1', models.ImageField(blank=True, null=True, upload_to=anunturi.models.post_adoption_photo_upload_to, verbose_name='Poza 1')),
                ('poza_2', models.ImageField(blank=True, null=True, upload_to=anunturi.models.post_adoption_photo_upload_to, verbose_name='Poza 2')),
                ('poza_3', models.ImageField(blank=True, null=True, upload_to=anunturi.models.post_adoption_photo_upload_to, verbose_name='Poza 3')),
                ('adoption_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_responses', to='anunturi.adoptionrequest')),
            ],
            options={
                'verbose_name': 'Răspuns verificare post-adopție',
                'verbose_name_plural': 'Răspunsuri verificare post-adopție',
                'ordering': ['-data_raspuns'],
            },
        ),
    ]
