# Generated by Django 6.0.2 on 2026-02-14 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0013_verificare_post_adoptie_form'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='added_by_user',
            field=models.ForeignKey(blank=True, help_text='Setat când anunțul e adăugat de o persoană fizică (limite lunare).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
