# Generated by Django 6.0.2 on 2026-02-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0016_signup_verification_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data tranzacției')),
                ('tip', models.CharField(choices=[('platit', 'Plătit'), ('donat', 'Donat')], max_length=10, verbose_name='Tip')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sumă (RON)')),
                ('descriere', models.CharField(blank=True, max_length=300, verbose_name='Descriere')),
                ('cui', models.CharField(blank=True, help_text='Ex: RO1234567 sau 1234567 – pentru match cu profil ONG/SRL.', max_length=20, verbose_name='CUI / CIF (RO sau cifre)')),
                ('telefon', models.CharField(blank=True, help_text='Pentru match cu profil persoană fizică (normalizat: doar cifre).', max_length=30, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Tranzacție financiară',
                'verbose_name_plural': 'Tranzacții financiare',
                'ordering': ['-data'],
            },
        ),
    ]
