# Generated by Django 6.0.2 on 2026-02-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anunturi', '0017_add_financial_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionrequest',
            name='doreste_cazare_medicala_toiletare',
            field=models.BooleanField(default=False, verbose_name='Dorește servicii medicale și toaletare (serviciu platformă)'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='doreste_transport',
            field=models.BooleanField(default=False, verbose_name='Ridicăm noi și transportăm contra cost la client'),
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='ridicare_personala',
            field=models.BooleanField(default=False, help_text='Clientul vine la adăpost. După aprobare, relația continuă direct între adăpost și client.', verbose_name='Ridicare personală, mă deplasez eu la locație'),
        ),
    ]
